import type { KnowledgeExercise } from "./knowledgeTypes";

/**
 * PHASE 2 KNOWLEDGE FIXTURES — pull catalogue (back, lats, traps).
 *
 * "BACK" is deliberately not one target. These entries separate lat-focused
 * vertical pulling, lat-focused shoulder extension, horizontal pulling,
 * mid-back retraction, lower-trap work, upper-trap work and rear-deltoid work,
 * so a future planner can compose a back session out of distinct roles instead
 * of three interchangeable rows.
 */

export const PULL_EXERCISES: readonly KnowledgeExercise[] = [
  {
    slug: "lat_pulldown_wide_grip",
    name: "Wide-grip lat pulldown",
    aliases: ["lat pulldown", "wide grip pulldown", "pulldown"],
    variationKey: "lat_pulldown:wide_grip_pronated",
    variationLabel: "Wide grip, pronated",
    category: "compound",
    movementPattern: "vertical_pull",
    primaryMovementFunction: "vertical_pull",
    movementFunctions: ["vertical_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "vertical_pull", "lat_emphasis_pull", "hypertrophy_movement"],
    equipment: ["lat_pulldown_machine"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Machine vertical pull with a wide pronated grip; the standard lat-emphasis pulling movement.",
    relations: [
      {
        muscle: "latissimus_dorsi",
        role: "primary_mover",
        weight: 0.8,
        emphasis: "lengthened_position",
        confidence: 0.85,
        notes: "Overhead stretch at the top is what makes this a lengthened-position pull.",
      },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.45, confidence: 0.85 },
      { muscle: "teres_major", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
      { muscle: "deltoid_rear", role: "supporting", weight: 0.15, confidence: 0.7 },
      { muscle: "trapezius", role: "supporting", weight: 0.15, confidence: 0.7 },
    ],
    structureRelations: [
      {
        muscle: "biceps_brachii",
        structure: "long_head",
        role: "secondary_mover",
        weight: 0.15,
        emphasis: "structure_biased",
        confidence: 0.65,
        notes: "Shoulder is extended overhead here, which lengthens the long head slightly.",
      },
    ],
    form: {
      setup: "Adjust the thigh pad so your legs are pinned and the seat is set for a slight lean back.",
      body_position: "Sit tall with a small lean back from the hips, chest up.",
      grip: "Wide overhand grip well outside shoulder width.",
      start_position: "Arms extended overhead with the shoulders actively depressed, not shrugged.",
      movement_path: "Pull the bar to the upper chest, leading with the elbows, then let it rise back overhead.",
      joint_path: "Shoulder adducts and extends downward; elbows travel down and back.",
      range_of_motion: "Reach full overhead extension at the top and pull to the collarbone at the bottom.",
      tempo_and_control: "Two seconds up, three seconds down to keep tension in the stretched position.",
      breathing: "Exhale as you pull down, inhale on the return overhead.",
      end_position: "Bar near the upper chest, elbows pointing down and back.",
      common_mistakes: "Leaning far back into a row, shrugging at the top, and bouncing the bar.",
      coaching_cues: ["Chest up, shoulders down", "Pull the elbows to your back pockets", "Reach tall at the top"],
      intended_target: "Latissimus dorsi with biceps and teres major contributing.",
      safety_notes: "Wipe the seat and the bar before loading; an overhead stretch with a heavy bar is not worth a slipping plate.",
    },
  },
  {
    slug: "lat_pulldown_neutral_grip",
    name: "Neutral-grip lat pulldown",
    aliases: ["close grip pulldown", "neutral pulldown"],
    variationKey: "lat_pulldown:neutral_grip",
    variationLabel: "Neutral grip, close handles",
    category: "compound",
    movementPattern: "vertical_pull",
    primaryMovementFunction: "vertical_pull",
    movementFunctions: ["vertical_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "vertical_pull", "lat_emphasis_pull", "hypertrophy_movement"],
    equipment: ["lat_pulldown_machine"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Neutral-grip vertical pull; same lat path as the wide-grip pulldown with a shorter lever and less upper-arm tension.",
    relations: [
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.8, emphasis: "lengthened_position", confidence: 0.85 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.5, confidence: 0.8 },
      { muscle: "teres_major", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
      { muscle: "brachialis", role: "supporting", weight: 0.2, confidence: 0.7 },
    ],
    form: {
      setup: "Set the thigh pad and sit tall with a slight hip hinge backward.",
      body_position: "Chest up, shoulders depressed, feet flat.",
      grip: "Neutral (palms facing each other) on the parallel handles.",
      start_position: "Arms overhead and extended, scapulae pulled down.",
      movement_path: "Pull the handles toward the upper chest, then let the shoulders rise back overhead.",
      joint_path: "Shoulder adducts and extends; elbows stay close to the body.",
      range_of_motion: "Full overhead reach at the top, handles to the collarbone at the bottom.",
      tempo_and_control: "Two seconds down, three seconds up.",
      breathing: "Exhale on the pull, inhale as you reach overhead.",
      end_position: "Handles at the upper chest, torso upright.",
      common_mistakes: "Rocking back, shrugging, and turning the neutral grip into a half-curl.",
      coaching_cues: ["Keep the shoulders away from the ears", "Pull to the collarbone, not the chin"],
      intended_target: "Latissimus dorsi pulling volume with a grip that spares the wrists and forearms.",
      safety_notes: "Use straps only if the grip fails; straps that fail mid-set are the real hazard.",
    },
  },
  {
    slug: "cable_pulldown_single_arm",
    name: "Single-arm cable pulldown",
    aliases: ["unilateral cable pulldown", "one arm lat pulldown"],
    variationKey: "cable_pulldown:single_arm",
    variationLabel: "Single arm, kneeling stance",
    category: "compound",
    movementPattern: "vertical_pull",
    primaryMovementFunction: "vertical_pull",
    movementFunctions: ["vertical_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "vertical_pull", "lat_emphasis_pull", "accessory_movement"],
    unilateral: true,
    equipment: ["cable_machine"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Unilateral vertical pull that removes the stronger side from hiding the weaker one.",
    relations: [
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.8, emphasis: "lengthened_position", confidence: 0.85 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.45, confidence: 0.8 },
      { muscle: "teres_major", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
    ],
    form: {
      setup: "Attach a single handle to a high pulley and take a half-kneeling stance beside the cable.",
      body_position: "One knee down, torso upright, free hand braced on the thigh.",
      grip: "Single-hand grip with the palm facing the body.",
      start_position: "Working arm extended overhead with the shoulder reaching tall.",
      movement_path: "Pull the handle down toward the hip, then let it rise overhead under control.",
      joint_path: "Shoulder adducts and extends; the elbow tracks close to the body.",
      range_of_motion: "Full overhead extension at the top, hand near the hip at the bottom.",
      tempo_and_control: "Two seconds down, three seconds up.",
      breathing: "Exhale as you pull down, inhale on the return.",
      end_position: "Handle at the hip, torso tall, shoulder down.",
      common_mistakes: "Twisting the torso, shrugging, and rushing the overhead stretch.",
      coaching_cues: ["Square the hips", "Reach tall before you pull", "Keep the torso still"],
      intended_target: "Latissimus dorsi per side, useful for side-to-side balance.",
      safety_notes: "Do not let the stacked weight fall back onto your hand when you fail a rep; set the stack between arms.",
    },
  },
  {
    slug: "pull_up",
    name: "Pull-up",
    aliases: ["pullup", "chin over bar"],
    variationKey: "pull_up:overhand_bodyweight",
    variationLabel: "Overhand, bodyweight",
    category: "compound",
    movementPattern: "vertical_pull",
    primaryMovementFunction: "vertical_pull",
    movementFunctions: ["vertical_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "vertical_pull", "lat_emphasis_pull", "primary_strength_movement"],
    equipment: ["pull_up_bar"],
    stabilityDemand: "high",
    loadingCharacteristic: "bodyweight_external_load",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Bodyweight vertical pull; the highest-difficulty lat-focused movement in the catalog.",
    relations: [
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.8, emphasis: "lengthened_position", confidence: 0.85 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.5, confidence: 0.85 },
      { muscle: "teres_major", role: "secondary_mover", weight: 0.3, confidence: 0.75 },
      { muscle: "forearm_flexors", role: "supporting", weight: 0.3, confidence: 0.8 },
      { muscle: "rhomboid_major", role: "stabilizer", weight: 0.15, confidence: 0.7 },
    ],
    form: {
      setup: "Grip the bar slightly wider than shoulder width and hang with straight arms.",
      body_position: "Active hang with the shoulders elevated away from the ears, ribs down.",
      grip: "Overhand grip, palms facing away.",
      start_position: "Full hang with the scapulae actively depressed.",
      movement_path: "Pull the chest toward the bar until the chin clears it, then lower to a full hang.",
      joint_path: "Shoulder adducts and extends; elbows travel down toward the ribs.",
      range_of_motion: "Full hang at the bottom and chin over the bar at the top — no partials for the catalog entry.",
      tempo_and_control: "Pull fast enough to clear the bar, lower for at least two seconds.",
      breathing: "Exhale as you pull up, inhale as you lower.",
      end_position: "Chin above the bar, shoulders still down.",
      common_mistakes: "Kipping, swinging the legs, and stopping short of a full hang.",
      coaching_cues: ["Start each rep from a straight-arm hang", "Pull the chest to the bar", "Squeeze the glutes"],
      intended_target: "Latissimus dorsi and upper-back pulling strength in its most demanding form.",
      safety_notes: "Use a spotter or band assistance rather than kipping if the shoulder end range is painful.",
    },
  },
  {
    slug: "assisted_pull_up",
    name: "Assisted pull-up",
    aliases: ["assisted chin up", "machine assisted pull up"],
    variationKey: "assisted_pull_up:counterweighted",
    variationLabel: "Counterweighted assistance",
    category: "compound",
    movementPattern: "vertical_pull",
    primaryMovementFunction: "vertical_pull",
    movementFunctions: ["vertical_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "vertical_pull", "lat_emphasis_pull", "accessory_movement"],
    equipment: ["assisted_pull_up_machine"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Vertical pull with counterweight assistance; the accessible route to pulling volume.",
    relations: [
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.75, emphasis: "lengthened_position", confidence: 0.8 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.45, confidence: 0.8 },
      { muscle: "teres_major", role: "secondary_mover", weight: 0.3, confidence: 0.75 },
    ],
    form: {
      setup: "Set the knee pad so the feet clear the floor but the pad is under the thighs.",
      body_position: "Hanging with the torso tall and the ribs down.",
      grip: "Neutral or overhand grip at shoulder width.",
      start_position: "Arms extended with the shoulders depressed.",
      movement_path: "Pull up until the chest approaches the bar, then lower under control.",
      joint_path: "Shoulder adducts and extends; elbows pull down toward the ribs.",
      range_of_motion: "Arms extended at the bottom, chest near the bar at the top.",
      tempo_and_control: "Two seconds down, controlled pull up.",
      breathing: "Exhale as you pull, inhale as you lower.",
      end_position: "Chest near the bar with the torso quiet.",
      common_mistakes: "Kicking off the floor, leaning back excessively, and choosing far too much assistance.",
      coaching_cues: ["Lean the chest forward", "Pull with the elbows, not the hands"],
      intended_target: "Latissimus dorsi pulling volume for users who cannot yet do a full pull-up.",
      safety_notes: "Reduce assistance before the set gets too easy to feel; assistance that is too high teaches nothing.",
    },
  },
  {
    slug: "barbell_bent_over_row",
    name: "Barbell bent-over row",
    aliases: ["bent over row", "BBR", "barbell row"],
    variationKey: "barbell_row:hip_hinged",
    variationLabel: "Hip-hinged, over-grip",
    category: "compound",
    movementPattern: "horizontal_pull",
    primaryMovementFunction: "horizontal_pull",
    movementFunctions: ["horizontal_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "horizontal_pull", "primary_strength_movement"],
    equipment: ["barbell"],
    stabilityDemand: "high",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Heavy horizontal pull from a hip hinge; mid-back and lat leaning strength movement.",
    relations: [
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.6, confidence: 0.8 },
      { muscle: "rhomboid_major", role: "secondary_mover", weight: 0.45, confidence: 0.8 },
      { muscle: "trapezius", role: "secondary_mover", weight: 0.4, confidence: 0.8 },
      { muscle: "rhomboid_minor", role: "secondary_mover", weight: 0.25, confidence: 0.75 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.35, confidence: 0.8 },
      { muscle: "deltoid_rear", role: "supporting", weight: 0.25, confidence: 0.7 },
    ],
    structureRelations: [
      {
        muscle: "trapezius",
        structure: "middle_region",
        role: "secondary_mover",
        weight: 0.2,
        emphasis: "structure_biased",
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Hold the bar with an overhand grip slightly wider than the thighs and hinge at the hips.",
      body_position: "Back flat and near parallel to the floor, knees bent, neck in line with the spine.",
      grip: "Overhand grip just outside knee width.",
      start_position: "Arms extended with the bar hanging below the shoulders.",
      movement_path: "Pull the bar to the lower ribs/upper abdomen, elbows flaring, then lower it under control.",
      joint_path: "Shoulder extends behind the torso; elbows travel past the ribs.",
      range_of_motion: "Lower until you feel a strong lat and upper-back stretch without the back rounding.",
      tempo_and_control: "Lower for at least two seconds; no bouncing.",
      breathing: "Exhale as you pull, inhale as you lower.",
      end_position: "Bar at the lower ribs, torso still hinged and back flat.",
      common_mistakes: "Rounding the back, standing up on every rep, and shrugging toward the bar.",
      coaching_cues: ["Push the hips back", "Pull to the hips, not the chest", "Chest stays proud"],
      intended_target: "Mid-back and lat horizontal pulling strength.",
      safety_notes: "Use a chest-supported pad or a lower load if the lower back cannot stay neutral — the hinge is a prerequisite, not a preference.",
    },
  },
  {
    slug: "seated_cable_row",
    name: "Seated cable row",
    aliases: ["cable row", "seated row"],
    variationKey: "seated_cable_row:chest_supported",
    variationLabel: "Chest pad, close-grip",
    category: "compound",
    movementPattern: "horizontal_pull",
    primaryMovementFunction: "horizontal_pull",
    movementFunctions: ["horizontal_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "horizontal_pull", "upper_back_retraction", "hypertrophy_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Supported horizontal pull with constant tension; a staple mid-back builder.",
    relations: [
      { muscle: "rhomboid_major", role: "primary_mover", weight: 0.6, emphasis: "structure_biased", confidence: 0.8 },
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.55, confidence: 0.8 },
      { muscle: "trapezius", role: "secondary_mover", weight: 0.4, confidence: 0.8 },
      { muscle: "rhomboid_minor", role: "secondary_mover", weight: 0.3, confidence: 0.75 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
      { muscle: "deltoid_rear", role: "supporting", weight: 0.2, confidence: 0.7 },
    ],
    structureRelations: [
      {
        muscle: "trapezius",
        structure: "middle_region",
        role: "secondary_mover",
        weight: 0.2,
        emphasis: "structure_biased",
        confidence: 0.75,
      },
      {
        muscle: "trapezius",
        structure: "lower_region",
        role: "supporting",
        weight: 0.15,
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Set the chest pad so it supports you at mid-chest and attach a close-grip handle.",
      body_position: "Torso upright against the pad, ribs down, hips anchored.",
      grip: "Neutral or close overhand grip.",
      start_position: "Arms extended forward with the shoulders reaching forward but not shrugged.",
      movement_path: "Pull the handle to the lower ribs, then let it travel forward until the shoulders protract.",
      joint_path: "Shoulder extends behind the torso; the scapulae retract then protract.",
      range_of_motion: "Full forward reach at the top and handle to the lower ribs at the bottom.",
      tempo_and_control: "Two seconds out, three seconds back to keep the stretched phase loaded.",
      breathing: "Exhale as you pull, inhale as you reach forward.",
      end_position: "Handle against the lower ribs, chest tall.",
      common_mistakes: "Leaning back and turning it into a shrug, and cutting the forward reach.",
      coaching_cues: ["Shoulder blades first", "Keep the torso fixed", "Reach forward fully"],
      intended_target: "Mid-back, rhomboids and lats with the chest supported so the upper back does the work.",
      safety_notes: "Do not use the leg drive; if the torso moves, the weight is too heavy.",
    },
  },
  {
    slug: "chest_supported_dumbbell_row",
    name: "Chest-supported dumbbell row",
    aliases: ["incline DB row", "chest supported row"],
    variationKey: "dumbbell_row:chest_supported",
    variationLabel: "Chest-supported, neutral grip",
    category: "compound",
    movementPattern: "horizontal_pull",
    primaryMovementFunction: "horizontal_pull",
    movementFunctions: ["horizontal_pull", "elbow_flexion", "shoulder_extension"],
    roles: ["compound_movement", "horizontal_pull", "upper_back_retraction", "hypertrophy_movement"],
    equipment: ["dumbbells", "adjustable_bench"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Horizontal pull with the chest supported, isolating the upper back from lower-back fatigue.",
    relations: [
      { muscle: "rhomboid_major", role: "primary_mover", weight: 0.6, confidence: 0.8 },
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.5, confidence: 0.8 },
      { muscle: "trapezius", role: "secondary_mover", weight: 0.4, confidence: 0.8 },
      { muscle: "deltoid_rear", role: "secondary_mover", weight: 0.25, confidence: 0.75 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.3, confidence: 0.8 },
    ],
    form: {
      setup: "Set the bench to roughly 30–45° and lie chest-down with dumbbells hanging below the shoulders.",
      body_position: "Chest and thighs on the pad, back neutral, neck in line with the spine.",
      grip: "Neutral grip with soft elbows.",
      start_position: "Arms extended toward the floor beneath the shoulders.",
      movement_path: "Row the dumbbells to the ribs, elbows flaring, then lower to a full stretch.",
      joint_path: "Shoulder extends behind the torso while the chest stays on the pad.",
      range_of_motion: "Lower until the dumbbells pass beneath the shoulders for a full upper-back stretch.",
      tempo_and_control: "Two seconds down, one second up.",
      breathing: "Exhale as you row, inhale as you lower.",
      end_position: "Dumbbells at the ribs, elbows above the torso.",
      common_mistakes: "Shrugging toward the armpits and lifting the chest off the pad to heave the weight.",
      coaching_cues: ["Elbows wide, not tucked", "Chest stays glued to the pad", "Lower to the stretch"],
      intended_target: "Mid-back and rear delts without lower-back involvement.",
      safety_notes: "Do not bounce the dumbbells off the floor; the stretch is the point, not the drop.",
    },
  },
  {
    slug: "straight_arm_cable_pulldown",
    name: "Straight-arm cable pulldown",
    aliases: ["straight arm pulldown", "SATP"],
    variationKey: "cable_pulldown:straight_arm",
    variationLabel: "Straight arm, high pulley",
    category: "other",
    movementPattern: "horizontal_pull",
    primaryMovementFunction: "straight_arm_pull",
    movementFunctions: ["straight_arm_pull", "shoulder_extension", "shoulder_abduction"],
    roles: ["accessory_movement", "lower_trap_emphasis", "hypertrophy_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Shoulder extension with a fixed elbow; the practical way to bias the lower lats and lower traps.",
    relations: [
      { muscle: "latissimus_dorsi", role: "primary_mover", weight: 0.6, emphasis: "lengthened_position", confidence: 0.75 },
      { muscle: "trapezius", role: "secondary_mover", weight: 0.3, emphasis: "lower_range_bias", confidence: 0.75 },
      { muscle: "deltoid_rear", role: "supporting", weight: 0.15, confidence: 0.7 },
    ],
    structureRelations: [
      {
        muscle: "trapezius",
        structure: "lower_region",
        role: "secondary_mover",
        weight: 0.2,
        emphasis: "lower_range_bias",
        confidence: 0.75,
        notes: "Lower-trap contribution; not a separate lower-trap isolation movement.",
      },
    ],
    form: {
      setup: "Attach a straight bar to a high pulley and step forward until the arms are extended overhead.",
      body_position: "Feet staggered, knees soft, torso upright with a slight hip hinge.",
      grip: "Overhand grip on the bar, arms almost straight.",
      start_position: "Arms angled up and forward, shoulder blades gently set.",
      movement_path: "Drive the bar down to the thighs by extending the shoulders, then let it rise overhead.",
      joint_path: "Shoulder extends with the elbows locked softly and held in place.",
      range_of_motion: "Reach as far overhead as comfortable at the top, bar to the thighs at the bottom.",
      tempo_and_control: "Two seconds down, three seconds up.",
      breathing: "Exhale as you press the bar down, inhale on the return.",
      end_position: "Bar brushing the thighs, torso still upright.",
      common_mistakes: "Letting the elbows bend into a pulldown, leaning back, and shrugging at the bottom.",
      coaching_cues: ["Lock the elbows", "Push the bar to your thighs", "Stand tall"],
      intended_target: "Lat lower-region and lower-trap work with a straight elbow.",
      safety_notes: "Keep the elbows soft rather than locked; a hard elbow lock turns the joint into a lever.",
    },
  },
  {
    slug: "kettlebell_shrug",
    name: "Kettlebell shrug",
    aliases: ["shrug", "KB shrug"],
    variationKey: "kettlebell_shrug:double_handle",
    variationLabel: "Two kettlebells at the sides",
    category: "other",
    movementPattern: "other",
    primaryMovementFunction: "shoulder_shrug",
    movementFunctions: ["shoulder_shrug"],
    roles: ["accessory_movement", "upper_trap_emphasis"],
    equipment: ["kettlebell"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Direct upper-trap work; the honest answer to 'I want thicker traps'.",
    relations: [
      { muscle: "trapezius", role: "primary_mover", weight: 0.75, emphasis: "upper_range_bias", confidence: 0.8 },
      { muscle: "forearm_flexors", role: "supporting", weight: 0.25, confidence: 0.75 },
    ],
    structureRelations: [
      {
        muscle: "trapezius",
        structure: "upper_region",
        role: "primary_mover",
        weight: 0.6,
        emphasis: "upper_range_bias",
        confidence: 0.8,
        notes: "Upper-trap-biased contribution; the middle and lower regions assist.",
      },
      {
        muscle: "trapezius",
        structure: "middle_region",
        role: "supporting",
        weight: 0.15,
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Stand tall holding a kettlebell in each hand beside the thighs.",
      body_position: "Feet hip-width, knees softly bent, torso upright.",
      grip: "Neutral hook grip on the kettlebell handles.",
      start_position: "Arms hanging straight at the sides, shoulders relaxed.",
      movement_path: "Elevate the shoulders straight up toward the ears, then lower them fully.",
      joint_path: "Shoulder girdle elevates and depresses; the arms stay straight.",
      range_of_motion: "Shrug as high as comfortable without rolling the shoulders, and lower to a full stretch.",
      tempo_and_control: "One second up, two seconds down, pause at the bottom.",
      breathing: "Exhale on the shrug, inhale as the shoulders come down.",
      end_position: "Shoulders fully depressed between reps.",
      common_mistakes: "Rolling the shoulders in circles instead of shrugging, and bending the elbows.",
      coaching_cues: ["Straight arms", "Up with the traps, not forward", "Let them drop all the way"],
      intended_target: "Upper trapezius development for neck-to-shoulder thickness.",
      safety_notes: "Keep the load close to the body; a shrug with a heavy, far-held bell stresses the lower back.",
    },
  },
];
