import type { KnowledgeExercise } from "./knowledgeTypes";

/**
 * PHASE 2 KNOWLEDGE FIXTURES — push catalogue (chest and shoulders).
 *
 * Each entry is a VARIATION, not a generic movement: "incline dumbbell press"
 * and "flat barbell bench press" are different exercises because they bias
 * different pectoralis regions, need different form, and substitute for
 * different things.
 */

export const PUSH_EXERCISES: readonly KnowledgeExercise[] = [
  {
    slug: "barbell_bench_press",
    name: "Barbell bench press",
    aliases: ["bench press", "flat bench press"],
    variationKey: "barbell_bench_press:flat_grip",
    variationLabel: "Flat bench, standard grip",
    category: "compound",
    movementPattern: "horizontal_push",
    primaryMovementFunction: "horizontal_press",
    movementFunctions: ["horizontal_press", "elbow_extension", "shoulder_adduction"],
    roles: ["compound_movement", "horizontal_push", "primary_strength_movement", "hypertrophy_movement"],
    equipment: ["barbell", "adjustable_bench"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Heavy horizontal press from a flat bench; the main sternal-pectoralis strength movement.",
    relations: [
      {
        muscle: "pectoralis_major",
        role: "primary_mover",
        weight: 0.8,
        emphasis: "shortened_position",
        confidence: 0.9,
        notes: "Sternal head carries most of a flat press; the clavicular head still contributes.",
      },
      { muscle: "triceps_brachii", role: "secondary_mover", weight: 0.45, confidence: 0.9 },
      { muscle: "deltoid_front", role: "secondary_mover", weight: 0.35, confidence: 0.85 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.2, confidence: 0.7 },
    ],
    structureRelations: [
      {
        muscle: "pectoralis_major",
        structure: "sternal_head",
        role: "primary_mover",
        weight: 0.55,
        emphasis: "structure_biased",
        confidence: 0.85,
        notes: "Biased from a flat press position; this is emphasis, not isolation.",
      },
      {
        muscle: "pectoralis_major",
        structure: "clavicular_head",
        role: "secondary_mover",
        weight: 0.25,
        confidence: 0.8,
      },
      {
        muscle: "triceps_brachii",
        structure: "lateral_head",
        role: "secondary_mover",
        weight: 0.28,
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Lie on a flat bench with your eyes under the bar; set your shoulder blades back and down.",
      body_position: "Feet flat and planted, glutes on the bench, upper back arched slightly and held.",
      grip: "Grip just outside shoulder width, palms facing down.",
      start_position: "Bar resting over the lower chest with the elbows tucked.",
      movement_path: "Lower the bar vertically to the lower chest, then press it back up and slightly toward your face.",
      joint_path: "Shoulder adducts and extends; elbows extend without drifting forward.",
      range_of_motion: "Lower until the upper arms are roughly parallel to the floor, without losing the shoulder-blade set.",
      tempo_and_control: "Control the descent for about two seconds and press without bouncing.",
      breathing: "Inhale on the way down, exhale as you press up.",
      end_position: "Arms extended above the chest without locking the elbows hard.",
      common_mistakes: "Flaring the elbows at the bottom, bouncing the bar, and letting the hips rise off the bench.",
      coaching_cues: ["Drive your feet into the floor", "Pull the bar back toward your face", "Keep the upper back pinned"],
      intended_target: "Mid-to-upper chest pressing power, with triceps and front delts contributing.",
      safety_notes: "Use a spotter or safeties for heavy singles; do not attempt maximal loads with a spotter absent.",
    },
  },
  {
    slug: "incline_dumbbell_press",
    name: "Incline dumbbell press",
    aliases: ["incline DB press", "incline bench press"],
    variationKey: "incline_dumbbell_press:30_degree",
    variationLabel: "30° incline, neutral-friendly grip",
    category: "compound",
    movementPattern: "horizontal_push",
    primaryMovementFunction: "incline_press",
    movementFunctions: ["incline_press", "horizontal_press", "elbow_extension", "shoulder_adduction"],
    roles: [
      "compound_movement",
      "upper_chest_press",
      "hypertrophy_movement",
      "horizontal_push",
    ],
    equipment: ["dumbbells", "adjustable_bench"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Presses from a low incline, biasing the clavicular (upper) chest region.",
    relations: [
      {
        muscle: "pectoralis_major",
        role: "primary_mover",
        weight: 0.75,
        emphasis: "lengthened_position",
        confidence: 0.85,
        notes: "The incline lowers the line of pull toward the clavicular head.",
      },
      { muscle: "deltoid_front", role: "secondary_mover", weight: 0.45, confidence: 0.85 },
      { muscle: "triceps_brachii", role: "secondary_mover", weight: 0.4, confidence: 0.85 },
    ],
    structureRelations: [
      {
        muscle: "pectoralis_major",
        structure: "clavicular_head",
        role: "primary_mover",
        weight: 0.5,
        emphasis: "structure_biased",
        confidence: 0.85,
        notes: "Upper-chest-biased contribution, not isolation.",
      },
      {
        muscle: "pectoralis_major",
        structure: "sternal_head",
        role: "secondary_mover",
        weight: 0.25,
        confidence: 0.8,
      },
    ],
    form: {
      setup: "Set the bench to roughly 30°, sit back, and walk the dumbbells to your shoulders.",
      body_position: "Back flat on the pad, feet planted, ribs down so the lower back stays in contact.",
      grip: "Hold the dumbbells at shoulder height with palms facing forward or neutral.",
      start_position: "Dumbbells resting at the shoulders with the elbows slightly behind the torso.",
      movement_path: "Press up and slightly inward until the dumbbells meet above the upper chest, then lower under control.",
      joint_path: "Elbows extend toward the midline rather than flaring straight out to the sides.",
      range_of_motion: "Lower until you feel a strong stretch across the upper chest, not until the shoulders round.",
      tempo_and_control: "Lower for two to three seconds; press without shrugging.",
      breathing: "Inhale on the descent, exhale on the press.",
      end_position: "Dumbbells above the upper chest with the elbows softly bent.",
      common_mistakes: "Setting the incline too steep, flaring the elbows, and lifting the hips off the pad.",
      coaching_cues: ["Squeeze the bench with your glutes", "Bring the dumbbells toward each other at the top"],
      intended_target: "Upper chest with meaningful triceps and front-deltoid contribution.",
      safety_notes: "Dropping the dumbbells outward after a hard set is the most common way to injure the shoulder here.",
    },
  },
  {
    slug: "machine_chest_press",
    name: "Machine chest press",
    aliases: ["chest press machine", "machine press"],
    variationKey: "machine_chest_press:seated",
    variationLabel: "Seated machine, fixed path",
    category: "compound",
    movementPattern: "horizontal_push",
    primaryMovementFunction: "horizontal_press",
    movementFunctions: ["horizontal_press", "elbow_extension"],
    roles: ["compound_movement", "horizontal_push", "hypertrophy_movement"],
    equipment: ["chest_press_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Guided horizontal press; easiest way to load the chest pattern without stabiliser fatigue.",
    relations: [
      { muscle: "pectoralis_major", role: "primary_mover", weight: 0.7, confidence: 0.85 },
      { muscle: "triceps_brachii", role: "secondary_mover", weight: 0.4, confidence: 0.85 },
      { muscle: "deltoid_front", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
    ],
    structureRelations: [
      {
        muscle: "pectoralis_major",
        structure: "sternal_head",
        role: "primary_mover",
        weight: 0.4,
        emphasis: "structure_biased",
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Adjust the seat so the handles align with your mid-chest; set the weight last.",
      body_position: "Back and head against the pad, feet flat on the floor, shoulders depressed.",
      grip: "Palms facing forward or inward, fingers open rather than wrapped.",
      start_position: "Handles level with the lower chest, elbows bent.",
      movement_path: "Push the handles forward until your arms are extended, then return slowly.",
      joint_path: "Elbows extend along the machine's arc without shrugging the shoulders.",
      range_of_motion: "Use the full comfortable arc; stop at the first hint of shoulder discomfort.",
      tempo_and_control: "Three seconds in, one second out.",
      breathing: "Inhale as the handles return, exhale as you press.",
      end_position: "Arms extended with the shoulders still down.",
      common_mistakes: "Letting the shoulders roll forward at the top and bouncing the return.",
      coaching_cues: ["Keep your shoulders down", "Control the return"],
      intended_target: "Chest pressing volume with minimal stabiliser demand.",
      safety_notes: "Stop the set if the machine's range pulls the shoulder forward past your comfortable position.",
    },
  },
  {
    slug: "cable_fly",
    name: "Cable crossover",
    aliases: ["cable fly", "crossover", "pec deck fly"],
    variationKey: "cable_fly:high_to_low",
    variationLabel: "High-to-low crossover",
    category: "isolation",
    movementPattern: "horizontal_push",
    primaryMovementFunction: "horizontal_press",
    movementFunctions: ["horizontal_press", "shoulder_adduction"],
    roles: ["isolation_movement", "shortened_position_emphasis", "hypertrophy_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "shortened_emphasised",
    summary: "Constant-tension chest fly; the clearest shortened-position emphasis in the catalog.",
    relations: [
      {
        muscle: "pectoralis_major",
        role: "primary_mover",
        weight: 0.85,
        emphasis: "shortened_position",
        confidence: 0.85,
        notes: "Emphasis is on the adducted, shortened position; the stretch is limited.",
      },
      { muscle: "deltoid_front", role: "supporting", weight: 0.2, confidence: 0.75 },
    ],
    structureRelations: [
      {
        muscle: "pectoralis_major",
        structure: "sternal_head",
        role: "primary_mover",
        weight: 0.4,
        emphasis: "shortened_position",
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Set both pulleys slightly above shoulder height and take a staggered stance.",
      body_position: "Soft knee bend, ribs down, torso upright with a small forward lean.",
      grip: "Handle in each hand with palms facing each other.",
      start_position: "Arms open and slightly behind the chest line, elbows softly bent.",
      movement_path: "Sweep the hands together in front of the lower chest, crossing slightly past each other.",
      joint_path: "Shoulder adducts across the body while the elbows keep a fixed, slight bend.",
      range_of_motion: "Open until you feel a stretch without the shoulders rolling forward; finish with the hands near each other.",
      tempo_and_control: "Two seconds in, two seconds out, no bounce at the crossover.",
      breathing: "Exhale as you bring the hands together, inhale as they open.",
      end_position: "Hands crossed in front of the lower chest.",
      common_mistakes: "Using the arms to heave the weight, going too heavy, and turning it into a press.",
      coaching_cues: ["Think about the chest doing the work", "Keep a soft elbow bend"],
      intended_target: "Shortened-position pectoralis work with a long, constant tension.",
      safety_notes: "Stop at the point where the front of the shoulder starts to pinch.",
    },
  },
  {
    slug: "push_up",
    name: "Push-up",
    aliases: ["press up", "pressup"],
    variationKey: "push_up:full_rom_bodyweight",
    variationLabel: "Full range of motion",
    category: "compound",
    movementPattern: "horizontal_push",
    primaryMovementFunction: "horizontal_press",
    movementFunctions: ["horizontal_press", "elbow_extension", "anti_extension"],
    roles: ["compound_movement", "horizontal_push", "accessory_movement"],
    equipment: ["bodyweight"],
    stabilityDemand: "high",
    loadingCharacteristic: "bodyweight_external_load",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "The default bodyweight horizontal press; trains the press pattern and anti-extension at once.",
    relations: [
      { muscle: "pectoralis_major", role: "primary_mover", weight: 0.6, confidence: 0.8 },
      { muscle: "triceps_brachii", role: "secondary_mover", weight: 0.4, confidence: 0.85 },
      { muscle: "deltoid_front", role: "secondary_mover", weight: 0.3, confidence: 0.8 },
      { muscle: "transversus_abdominis", role: "stabilizer", weight: 0.25, confidence: 0.7 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.2, confidence: 0.7 },
    ],
    form: {
      setup: "Place hands slightly wider than shoulder width on the floor and walk the feet back.",
      body_position: "One straight line from head to heels, glutes and ribs both gently set.",
      grip: "Hands under the lower chest, fingers spread.",
      start_position: "Arms extended, hands under the chest, body rigid.",
      movement_path: "Lower the chest between the hands until the elbows are about 90°, then press back up.",
      joint_path: "Elbows track back at roughly 45° rather than flaring straight out.",
      range_of_motion: "Lower until the chest is a fist's height from the floor, keeping the hips level.",
      tempo_and_control: "Two seconds down, one second up, no sagging.",
      breathing: "Inhale on the way down, exhale as you press up.",
      end_position: "Arms extended with the upper back still set.",
      common_mistakes: "Hips sagging or piking, elbows flaring to the sides, and half-range reps.",
      coaching_cues: ["Squeeze your glutes", "Elbows back, chest forward", "Move as one unit"],
      intended_target: "Horizontal pressing pattern plus whole-body bracing.",
      safety_notes: "Stop if the lower back sags — shorten the range rather than losing the position.",
    },
  },
  {
    slug: "barbell_overhead_press",
    name: "Barbell overhead press",
    aliases: ["OHP", "military press", "standing press"],
    variationKey: "barbell_overhead_press:standing",
    variationLabel: "Standing, seated-back stance",
    category: "compound",
    movementPattern: "vertical_push",
    primaryMovementFunction: "vertical_press",
    movementFunctions: ["vertical_press", "elbow_extension", "shoulder_abduction"],
    roles: ["compound_movement", "vertical_push", "primary_strength_movement", "hypertrophy_movement"],
    equipment: ["barbell"],
    stabilityDemand: "high",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Standing overhead press; the main vertical-push strength movement.",
    relations: [
      { muscle: "deltoid_front", role: "primary_mover", weight: 0.75, confidence: 0.85 },
      { muscle: "triceps_brachii", role: "secondary_mover", weight: 0.45, confidence: 0.85 },
      { muscle: "deltoid_side", role: "secondary_mover", weight: 0.25, confidence: 0.8 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.25, confidence: 0.75 },
      { muscle: "quadriceps", role: "stabilizer", weight: 0.15, confidence: 0.65 },
    ],
    structureRelations: [
      {
        muscle: "triceps_brachii",
        structure: "long_head",
        role: "secondary_mover",
        weight: 0.2,
        emphasis: "structure_biased",
        confidence: 0.7,
        notes: "The overhead position lengthens the long head; still a contribution.",
      },
    ],
    form: {
      setup: "Set the bar at the clavicle notch with a grip just outside shoulder width.",
      body_position: "Feet hip-width, glutes squeezed, ribs down, head forward.",
      grip: "Full grip on the bar with the thumbs wrapped underneath.",
      start_position: "Bar resting on the front of the shoulders, elbows slightly in front of the torso.",
      movement_path: "Press the bar up and slightly back until it passes over the mid-foot with the arms extended.",
      joint_path: "Elbows extend and move under the bar; the head moves back briefly and then returns.",
      range_of_motion: "Start with the bar at shoulder height and finish with straight arms over the mid-foot.",
      tempo_and_control: "Smooth press, no bounce out of the rack position.",
      breathing: "Inhale before the press, exhale as the bar passes the face.",
      end_position: "Arms extended overhead, bar over the mid-foot, glutes still squeezed.",
      common_mistakes: "Leaning back, letting the lower back arch, and pressing the bar forward of the feet.",
      coaching_cues: ["Push your head back through the window", "Squeeze the glutes hard", "Finish over the mid-foot"],
      intended_target: "Overhead pressing strength with triceps and side-deltoid contribution.",
      safety_notes: "Do not learn this with heavy loads; practise the lockout and the rack position first.",
    },
  },
  {
    slug: "dumbbell_seated_shoulder_press",
    name: "Seated dumbbell shoulder press",
    aliases: ["seated DB press", "shoulder press"],
    variationKey: "dumbbell_shoulder_press:seated",
    variationLabel: "Seated, back supported",
    category: "compound",
    movementPattern: "vertical_push",
    primaryMovementFunction: "vertical_press",
    movementFunctions: ["vertical_press", "elbow_extension", "shoulder_abduction"],
    roles: ["compound_movement", "front_delt_press", "hypertrophy_movement"],
    equipment: ["dumbbells", "adjustable_bench"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Supported overhead press that removes most of the lower-back demand from the standing press.",
    relations: [
      { muscle: "deltoid_front", role: "primary_mover", weight: 0.75, confidence: 0.85 },
      { muscle: "triceps_brachii", role: "secondary_mover", weight: 0.45, confidence: 0.85 },
      { muscle: "deltoid_side", role: "secondary_mover", weight: 0.3, confidence: 0.8 },
    ],
    form: {
      setup: "Sit with the back upright against the pad and the dumbbells resting on the thighs.",
      body_position: "Feet flat, back supported, ribs down.",
      grip: "Dumbbells at shoulder height, palms facing forward.",
      start_position: "Dumbbells at shoulder level with the elbows slightly in front of the torso.",
      movement_path: "Press up until the dumbbells meet overhead, then lower back to the shoulders.",
      joint_path: "Elbows extend upward without drifting behind the ears.",
      range_of_motion: "Lower until you feel a comfortable stretch at the top of the shoulder.",
      tempo_and_control: "Two seconds down, one second up.",
      breathing: "Inhale on the way down, exhale as you press.",
      end_position: "Dumbbells overhead with the elbows softly bent.",
      common_mistakes: "Flaring elbows well below shoulder height and shrugging at the top.",
      coaching_cues: ["Keep the upper arms roughly vertical", "Lower to ear level, not further"],
      intended_target: "Overhead pressing volume for the front delts with triceps involvement.",
      safety_notes: "Use a bench back support if you have lower-back issues; do not press behind the head.",
    },
  },
  {
    slug: "dumbbell_lateral_raise",
    name: "Dumbbell lateral raise",
    aliases: ["lateral raise", "side raise"],
    variationKey: "dumbbell_lateral_raise:seated",
    variationLabel: "Seated or standing, neutral grip",
    category: "isolation",
    primaryMovementFunction: "shoulder_abduction",
    movementFunctions: ["shoulder_abduction"],
    roles: ["isolation_movement", "lateral_delt_isolation", "hypertrophy_movement"],
    equipment: ["dumbbells"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Shoulder-abduction isolation for the lateral deltoid; the standard side-of-shoulder builder.",
    relations: [
      { muscle: "deltoid_side", role: "primary_mover", weight: 0.9, confidence: 0.9 },
      { muscle: "deltoid_front", role: "supporting", weight: 0.15, confidence: 0.7 },
      { muscle: "trapezius", role: "supporting", weight: 0.15, confidence: 0.75 },
    ],
    structureRelations: [
      {
        muscle: "trapezius",
        structure: "upper_region",
        role: "supporting",
        weight: 0.1,
        confidence: 0.7,
        notes: "Shrugging into the raise is exactly the error this relation exists to expose.",
      },
    ],
    form: {
      setup: "Sit or stand with dumbbells at your sides and a slight bend in the elbows.",
      body_position: "Torso upright, ribs down, shoulders gently depressed.",
      grip: "Neutral grip (palms facing each other) or whatever keeps tension best through the range.",
      start_position: "Dumbbells hanging in front of the thighs with soft knees.",
      movement_path: "Raise the arms out to the sides in a wide arc until the upper arms are near shoulder height.",
      joint_path: "Shoulder abducts with a fixed, small elbow bend; the forearms do not travel.",
      range_of_motion: "Raise to the height where the deltoid is shortened without shrugging; stop there.",
      tempo_and_control: "Two seconds up, three seconds down — the lowering phase is where the work is.",
      breathing: "Exhale as you raise, inhale as you lower.",
      end_position: "Upper arms near shoulder height, elbows still slightly bent, no shrug.",
      common_mistakes: "Swinging the torso, using momentum, and shrugging the traps to finish the rep.",
      coaching_cues: ["Lead with the elbows", "Think 'elbows to the ceiling', not 'hands up'", "Lower slowly"],
      intended_target: "Lateral deltoid size and shoulder width for physique goals.",
      safety_notes: "Light weight is correct here; a heavy raise is usually a swing, not a stimulus.",
    },
  },
  {
    slug: "cable_lateral_raise",
    name: "Cable lateral raise",
    aliases: ["cable side raise", "one-arm cable lateral raise"],
    variationKey: "cable_lateral_raise:single_arm",
    variationLabel: "Single arm, cross-body",
    category: "isolation",
    primaryMovementFunction: "shoulder_abduction",
    movementFunctions: ["shoulder_abduction"],
    roles: ["isolation_movement", "lateral_delt_isolation", "hypertrophy_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Unilateral cable abduction with tension that increases through the raise.",
    relations: [
      { muscle: "deltoid_side", role: "primary_mover", weight: 0.9, confidence: 0.85 },
      { muscle: "deltoid_front", role: "supporting", weight: 0.15, confidence: 0.7 },
      { muscle: "trapezius", role: "supporting", weight: 0.15, confidence: 0.7 },
    ],
    form: {
      setup: "Set a single handle on a low pulley and stand side-on to the machine.",
      body_position: "Slight forward lean, feet staggered, free hand resting on the thigh.",
      grip: "Single-arm grip on the handle with the palm facing inward.",
      start_position: "Arm across the front of the opposite thigh with a soft elbow.",
      movement_path: "Raise the arm up and slightly across the body until the upper arm reaches shoulder height.",
      joint_path: "Shoulder abducts and moves into a small horizontal adduction; elbow stays softly bent.",
      range_of_motion: "Start from a comfortable stretch and finish at shoulder height without shrugging.",
      tempo_and_control: "One second up, three seconds down.",
      breathing: "Exhale on the raise, inhale on the return.",
      end_position: "Upper arm level with the shoulder, torso still quiet.",
      common_mistakes: "Torso swinging, cutting the bottom of the range, and shrugging.",
      coaching_cues: ["Keep the ribs down", "Move only the shoulder"],
      intended_target: "Lateral deltoid work with uninterrupted tension.",
      safety_notes: "If the cable stack cannot reach a comfortable bottom position, the exercise is set up too high.",
    },
  },
  {
    slug: "machine_lateral_raise",
    name: "Machine lateral raise",
    aliases: ["lateral raise machine", "pec deck lateral"],
    variationKey: "machine_lateral_raise:upright",
    variationLabel: "Upright pad machine",
    category: "isolation",
    primaryMovementFunction: "shoulder_abduction",
    movementFunctions: ["shoulder_abduction"],
    roles: ["isolation_movement", "lateral_delt_isolation", "accessory_movement"],
    equipment: ["lateral_raise_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Guided abduction; the accessible fallback when a cable station is unavailable.",
    relations: [
      { muscle: "deltoid_side", role: "primary_mover", weight: 0.85, confidence: 0.8 },
      { muscle: "trapezius", role: "supporting", weight: 0.15, confidence: 0.7 },
    ],
    form: {
      setup: "Set the seat so the upper arms rest on the pad level with your shoulders.",
      body_position: "Back against the seat, feet flat, torso still.",
      grip: "Forearms resting on the pad, elbows slightly bent.",
      start_position: "Upper arms supported with the elbows just in front of the torso.",
      movement_path: "Open the arms outward until the elbows are roughly level with the shoulders.",
      joint_path: "Shoulder abducts with the elbow angle held constant.",
      range_of_motion: "Open as far as the pad allows without shrugging.",
      tempo_and_control: "Two seconds out, two seconds back.",
      breathing: "Exhale as the arms open, inhale as they return.",
      end_position: "Arms open, shoulders down.",
      common_mistakes: "Using the torso to heave the pad, and stopping far short of the open position.",
      coaching_cues: ["Lead with the elbows", "Pause for a beat at the top"],
      intended_target: "Lateral deltoid work when free weights or cables are not available.",
      safety_notes: "Keep the lower arms on the pad so the shoulder does not take the load awkwardly.",
    },
  },
  {
    slug: "face_pull",
    name: "Cable face pull",
    aliases: ["face pull", "rope face pull"],
    variationKey: "face_pull:rope_at_eye_level",
    variationLabel: "Rope attachment at eye level",
    category: "isolation",
    movementPattern: "horizontal_pull",
    primaryMovementFunction: "horizontal_pull",
    movementFunctions: ["horizontal_pull", "shoulder_extension", "shoulder_abduction"],
    roles: [
      "isolation_movement",
      "upper_back_retraction",
      "accessory_movement",
    ],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Rope pull to face height; the practical way to train rear delts and upper-back position.",
    relations: [
      { muscle: "deltoid_rear", role: "primary_mover", weight: 0.75, emphasis: "structure_biased", confidence: 0.85 },
      { muscle: "trapezius", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
      { muscle: "rhomboid_major", role: "secondary_mover", weight: 0.25, confidence: 0.75 },
      { muscle: "rhomboid_minor", role: "secondary_mover", weight: 0.2, confidence: 0.75 },
    ],
    structureRelations: [
      {
        muscle: "trapezius",
        structure: "middle_region",
        role: "secondary_mover",
        weight: 0.2,
        emphasis: "structure_biased",
        confidence: 0.75,
      },
      {
        muscle: "trapezius",
        structure: "upper_region",
        role: "supporting",
        weight: 0.15,
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Set a rope at roughly eye height and step back until the arms are extended forward.",
      body_position: "Feet staggered, knees soft, torso upright and slightly leaned back.",
      grip: "Both hands on the rope ends with an overhand grip.",
      start_position: "Arms extended in front of the chest at shoulder height.",
      movement_path: "Pull the rope toward the face, leading with the elbows and finishing with the hands beside the ears.",
      joint_path: "Shoulder extends and abducts horizontally while staying below the overhead position.",
      range_of_motion: "Finish with the upper arms level with the shoulders and the hands just past the ears.",
      tempo_and_control: "Slow pull, one-second hold at the end, slow return.",
      breathing: "Exhale on the pull, inhale on the return.",
      end_position: "Hands beside the ears, elbows level with the shoulders, ribs down.",
      common_mistakes: "Pulling too high into a shrug, and letting the lower back arch to reach further.",
      coaching_cues: ["Lead with the elbows", "Finish with the hands by your ears", "Pause and squeeze"],
      intended_target: "Rear deltoids and mid-to-upper back, useful for shoulder health and posture.",
      safety_notes: "Keep the pull below shoulder level to avoid turning it into an overhead shrug.",
    },
  },
  {
    slug: "bent_over_dumbbell_reverse_fly",
    name: "Bent-over dumbbell reverse fly",
    aliases: ["reverse fly", "rear delt fly", "butterfly"],
    variationKey: "bent_over_dumbbell_reverse_fly:hip_hinged",
    variationLabel: "Hip-hinged, chest-supported feel",
    category: "isolation",
    movementPattern: "horizontal_pull",
    primaryMovementFunction: "horizontal_pull",
    movementFunctions: ["horizontal_pull", "shoulder_abduction", "shoulder_extension"],
    roles: ["isolation_movement", "upper_back_retraction", "accessory_movement"],
    equipment: ["dumbbells"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Hip-hinged shoulder abduction isolating the rear deltoids.",
    relations: [
      { muscle: "deltoid_rear", role: "primary_mover", weight: 0.8, confidence: 0.8 },
      { muscle: "trapezius", role: "secondary_mover", weight: 0.25, confidence: 0.75 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.3, confidence: 0.75 },
    ],
    form: {
      setup: "Stand holding dumbbells in front of the thighs and hinge at the hips.",
      body_position: "Back flat and roughly parallel to the floor, knees softly bent, neck in line with the spine.",
      grip: "Neutral grip with a slight bend in the elbows held throughout.",
      start_position: "Arms hanging toward the floor beneath the shoulders.",
      movement_path: "Open the arms out to the sides until the upper arms reach shoulder height.",
      joint_path: "Shoulder abducts in the scapular plane with a fixed elbow bend.",
      range_of_motion: "Open until the upper arms are level with the torso, without shrugging.",
      tempo_and_control: "Two seconds out, three seconds back.",
      breathing: "Exhale as the arms open, inhale on the return.",
      end_position: "Upper arms level with the back, elbows still softly bent.",
      common_mistakes: "Rounding the back, using momentum, and turning it into a row.",
      coaching_cues: ["Long spine", "Lead with the elbows", "Pause at the top"],
      intended_target: "Rear deltoid isolation for shoulder balance and posture.",
      safety_notes: "Stop the set if the lower back rounds; use a chest-supported bench if needed.",
    },
  },
];
