import type { KnowledgeExercise } from "./knowledgeTypes";

/**
 * PHASE 2 KNOWLEDGE FIXTURES — arm catalogue (elbow flexors and extensors).
 *
 * The biceps and triceps entries are where head-specific reasoning has to be
 * honest. Each entry states which head or heads are *biased* or *contribute*,
 * never that a head is isolated, and the set is deliberately complementary:
 * a long-head-biased variation, a short-position variation and a brachialis/
 * elbow-flexor variation train different parts of the same joint.
 */

export const ARM_EXERCISES: readonly KnowledgeExercise[] = [
  {
    slug: "barbell_curl",
    name: "Barbell curl",
    aliases: ["BB curl", "standing barbell curl"],
    variationKey: "barbell_curl:standing_standard",
    variationLabel: "Standing, shoulder behind the torso",
    category: "isolation",
    primaryMovementFunction: "elbow_flexion",
    movementFunctions: ["elbow_flexion", "forearm_supination"],
    roles: ["isolation_movement", "hypertrophy_movement", "lengthened_position_emphasis"],
    equipment: ["barbell"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "partial_rom",
    summary: "Standing curl with the shoulder slightly behind the torso, biasing the long head.",
    relations: [
      { muscle: "biceps_brachii", role: "primary_mover", weight: 0.85, confidence: 0.85 },
      { muscle: "brachialis", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
      { muscle: "brachioradialis", role: "supporting", weight: 0.2, confidence: 0.75 },
      { muscle: "forearm_flexors", role: "supporting", weight: 0.25, confidence: 0.75 },
    ],
    structureRelations: [
      {
        muscle: "biceps_brachii",
        structure: "long_head",
        role: "primary_mover",
        weight: 0.45,
        emphasis: "structure_biased",
        confidence: 0.8,
        notes:
          "Standing with the shoulder behind the torso lengthens the long head through the bottom of the rep. This is a bias, not isolation.",
      },
      {
        muscle: "biceps_brachii",
        structure: "short_head",
        role: "secondary_mover",
        weight: 0.25,
        emphasis: "structure_biased",
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Hold the barbell with a shoulder-width supinated grip and stand with feet hip-width.",
      body_position: "Torso upright and still, elbows close to the ribs, shoulders behind the torso line.",
      grip: "Underhand (supinated) grip just outside shoulder width.",
      start_position: "Arms extended with the bar at thigh level.",
      movement_path: "Curl the bar toward the shoulders, then lower it slowly to full extension.",
      joint_path: "Only the elbow flexes; the upper arms stay pinned beside the torso.",
      range_of_motion: "Full extension at the bottom and the bar near the collarbone at the top.",
      tempo_and_control: "Three seconds down; do not let the bar swing.",
      breathing: "Exhale on the way up, inhale on the way down.",
      end_position: "Bar at the upper chest with the elbows still beside the body.",
      common_mistakes: "Swinging the torso, letting the elbows travel forward, and half-extending at the bottom.",
      coaching_cues: ["Pin the elbows to your sides", "Lower slower than you lift"],
      intended_target: "Biceps brachii with a long-head bias, plus brachialis and elbow-flexor contribution.",
      safety_notes: "Swinging a heavy curl is a lower-back exercise wearing a curl's clothes; keep the torso fixed.",
    },
  },
  {
    slug: "incline_dumbbell_curl",
    name: "Incline dumbbell curl",
    aliases: ["incline DB curl", "high incline curl"],
    variationKey: "incline_dumbbell_curl:high_incline",
    variationLabel: "High incline, long-head emphasis",
    category: "isolation",
    primaryMovementFunction: "elbow_flexion",
    movementFunctions: ["elbow_flexion", "shoulder_extension"],
    roles: ["isolation_movement", "lengthened_position_emphasis", "hypertrophy_movement"],
    equipment: ["dumbbells", "adjustable_bench"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Curl from a high incline so the biceps starts long — the clearest lengthened-position bias for the long head.",
    relations: [
      {
        muscle: "biceps_brachii",
        role: "primary_mover",
        weight: 0.85,
        emphasis: "lengthened_position",
        confidence: 0.85,
      },
      { muscle: "brachialis", role: "secondary_mover", weight: 0.3, confidence: 0.8 },
    ],
    structureRelations: [
      {
        muscle: "biceps_brachii",
        structure: "long_head",
        role: "primary_mover",
        weight: 0.5,
        emphasis: "lengthened_position",
        confidence: 0.85,
        notes:
          "The incline places the shoulder in extension so the long head spends more of the rep long. Bias, not isolation.",
      },
      {
        muscle: "biceps_brachii",
        structure: "short_head",
        role: "secondary_mover",
        weight: 0.2,
        emphasis: "shortened_position",
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Set the bench to 45–60°, sit back, and let the dumbbells hang behind the line of the torso.",
      body_position: "Back against the pad, chest up, arms extended and slightly behind the shoulders.",
      grip: "Supinated grip, palms facing forward.",
      start_position: "Arms fully extended with a strong stretch across the front of the shoulder.",
      movement_path: "Curl the dumbbells up toward the shoulders without swinging, then lower to full extension.",
      joint_path: "Elbows flex in place; the upper arms stay still against the torso line.",
      range_of_motion: "Full extension at the bottom — the stretch position is the point of this variation.",
      tempo_and_control: "Three seconds down, one second up.",
      breathing: "Exhale on the curl, inhale on the lower.",
      end_position: "Dumbbells near the shoulders with the back still on the pad.",
      common_mistakes: "Starting the reps with the arms already half-curled, and swinging.",
      coaching_cues: ["Let the dumbbells drop behind you", "Reach full extension", "No torso movement"],
      intended_target: "Biceps long-head-biased work performed from a lengthened position.",
      safety_notes: "Keep the shoulders down and back at the bottom; over-stretching the front of the shoulder causes impingement-style pain in some people.",
    },
  },
  {
    slug: "preacher_curl",
    name: "Preacher curl",
    aliases: ["preacher bench curl", "EZ preacher curl"],
    variationKey: "preacher_curl:pad_supported",
    variationLabel: "Pad-supported, upper-arm fixed",
    category: "isolation",
    primaryMovementFunction: "elbow_flexion",
    movementFunctions: ["elbow_flexion"],
    roles: ["isolation_movement", "shortened_position_emphasis", "hypertrophy_movement"],
    equipment: ["ez_bar", "adjustable_bench"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "shortened_emphasised",
    summary: "Curl with the upper arm supported in a shortened position; the complement to the incline curl.",
    relations: [
      {
        muscle: "biceps_brachii",
        role: "primary_mover",
        weight: 0.8,
        emphasis: "shortened_position",
        confidence: 0.8,
      },
      { muscle: "brachialis", role: "secondary_mover", weight: 0.3, confidence: 0.8 },
      { muscle: "brachioradialis", role: "supporting", weight: 0.2, confidence: 0.75 },
    ],
    structureRelations: [
      {
        muscle: "biceps_brachii",
        structure: "short_head",
        role: "secondary_mover",
        weight: 0.3,
        emphasis: "shortened_position",
        confidence: 0.75,
        notes:
          "With the shoulder neutral or slightly flexed and the elbow held forward, the short head carries more of the work than in a hanging curl. Still a contribution.",
      },
      {
        muscle: "biceps_brachii",
        structure: "long_head",
        role: "secondary_mover",
        weight: 0.3,
        emphasis: "shortened_position",
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Set the preacher pad to support the backs of the upper arms just above the elbows.",
      body_position: "Seated, back against the pad, chest upright.",
      grip: "EZ-bar underhand grip or dumbbells, elbows resting on the pad.",
      start_position: "Arms extended with the elbows on the pad and the upper arms supported.",
      movement_path: "Curl the bar toward the shoulders, then lower until the arms are almost straight.",
      joint_path: "Elbows flex and extend while staying planted on the pad; the upper arm cannot swing.",
      range_of_motion: "Lower until you feel a stretch in the biceps without the elbows lifting off the pad.",
      tempo_and_control: "Two seconds up, three seconds down.",
      breathing: "Exhale on the curl, inhale on the lower.",
      end_position: "Bar near the shoulders, elbows still in contact with the pad.",
      common_mistakes: "Letting the elbows drift off the pad and turning it into a normal curl.",
      coaching_cues: ["Elbows glued to the pad", "Control the lower", "Don't shrug"],
      intended_target: "Biceps work anchored in the shortened position, complementing lengthened-position work.",
      safety_notes: "Do not extend the elbows completely against the pad; hyperextension under load is unnecessary.",
    },
  },
  {
    slug: "spider_curl",
    name: "Spider curl",
    aliases: ["spider curl", "seated spider curl"],
    variationKey: "spider_curl:lean_forward",
    variationLabel: "Lean-forward, elbow behind the torso",
    category: "isolation",
    primaryMovementFunction: "elbow_flexion",
    movementFunctions: ["elbow_flexion"],
    roles: ["isolation_movement", "shortened_position_emphasis", "accessory_movement"],
    equipment: ["dumbbells"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "partial_rom",
    summary: "Seated curl with a forward lean and the elbows behind the torso, driving the short head and brachialis.",
    relations: [
      {
        muscle: "biceps_brachii",
        role: "primary_mover",
        weight: 0.8,
        emphasis: "shortened_position",
        confidence: 0.8,
      },
      { muscle: "brachialis", role: "secondary_mover", weight: 0.4, confidence: 0.8 },
    ],
    structureRelations: [
      {
        muscle: "biceps_brachii",
        structure: "short_head",
        role: "secondary_mover",
        weight: 0.35,
        emphasis: "shortened_position",
        confidence: 0.8,
        notes: "Elbows held behind the torso shorten the long head and favour the short head. Contribution, not isolation.",
      },
    ],
    form: {
      setup: "Sit on a flat bench holding dumbbells at your sides and lean the torso forward about 30°.",
      body_position: "Torso inclined, chest open, upper arms hanging down and slightly behind the torso.",
      grip: "Supinated grip with palms facing forward.",
      start_position: "Arms nearly straight with the elbows behind the torso line.",
      movement_path: "Curl the dumbbells up toward the chest, then lower partway under control.",
      joint_path: "Elbows stay in place and travel slightly forward; the upper arm does not move.",
      range_of_motion: "Curl to a strong contraction at the top; the lower position is deliberately partial.",
      tempo_and_control: "Two seconds up, three seconds down.",
      breathing: "Exhale on the curl, inhale on the lower.",
      end_position: "Dumbbells near the chest with the torso still inclined.",
      common_mistakes: "Standing up on every rep and swinging the elbows forward.",
      coaching_cues: ["Lean forward and stay there", "Elbows behind you", "Squeeze at the top"],
      intended_target: "Short-position biceps and brachialis contribution.",
      safety_notes: "Use a lighter load than a standing curl; the leverage advantage makes overloading easy.",
    },
  },
  {
    slug: "hammer_curl",
    name: "Hammer curl",
    aliases: ["neutral curl", "cross-body hammer curl"],
    variationKey: "hammer_curl:neutral_grip",
    variationLabel: "Neutral grip, elbow fixed",
    category: "isolation",
    primaryMovementFunction: "elbow_flexion",
    movementFunctions: ["elbow_flexion", "forearm_pronation"],
    roles: ["isolation_movement", "hypertrophy_movement", "accessory_movement"],
    equipment: ["dumbbells"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Neutral-grip curl; the practical way to train brachialis and the brachioradialis.",
    relations: [
      { muscle: "brachialis", role: "primary_mover", weight: 0.7, emphasis: "structure_biased", confidence: 0.8 },
      { muscle: "brachioradialis", role: "primary_mover", weight: 0.6, confidence: 0.8 },
      { muscle: "biceps_brachii", role: "secondary_mover", weight: 0.5, confidence: 0.85 },
      { muscle: "forearm_flexors", role: "supporting", weight: 0.2, confidence: 0.7 },
    ],
    form: {
      setup: "Stand holding dumbbells with the palms facing each other.",
      body_position: "Feet hip-width, torso upright, elbows pinned to the sides.",
      grip: "Neutral grip, thumbs up.",
      start_position: "Arms extended with the palms facing inward.",
      movement_path: "Curl the dumbbells up while keeping the palms facing each other, then lower slowly.",
      joint_path: "Elbows flex in place with no rotation at the forearm.",
      range_of_motion: "Full extension at the bottom, dumbbells near the shoulders at the top.",
      tempo_and_control: "Three seconds down, controlled lift.",
      breathing: "Exhale on the curl, inhale on the lower.",
      end_position: "Dumbbells at shoulder height with the palms still facing each other.",
      common_mistakes: "Letting the forearms rotate into a hammer grip cheat, and swinging.",
      coaching_cues: ["Knuckles forward, stay that way", "Elbows still", "Slow negative"],
      intended_target: "Brachialis and brachioradialis contribution alongside the biceps.",
      safety_notes: "The elbow stays flexed rather than fully straightened at the bottom; lockout is unnecessary here.",
    },
  },
  {
    slug: "cable_curl_underhand",
    name: "Underhand cable curl",
    aliases: ["cable curl", "low pulley curl"],
    variationKey: "cable_curl_underhand:low_pulley",
    variationLabel: "Low pulley, underhand",
    category: "isolation",
    primaryMovementFunction: "elbow_flexion",
    movementFunctions: ["elbow_flexion"],
    roles: ["isolation_movement", "hypertrophy_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Constant-tension cable curl; easy to load progressively without losing the stretch position.",
    relations: [
      { muscle: "biceps_brachii", role: "primary_mover", weight: 0.8, confidence: 0.85 },
      { muscle: "brachialis", role: "secondary_mover", weight: 0.35, confidence: 0.8 },
      { muscle: "forearm_flexors", role: "supporting", weight: 0.2, confidence: 0.7 },
    ],
    form: {
      setup: "Attach a straight bar to a low pulley and stand facing the stack.",
      body_position: "Torso upright, elbows tucked, feet staggered slightly for balance.",
      grip: "Underhand grip just outside shoulder width.",
      start_position: "Arms extended with the bar against the thighs.",
      movement_path: "Curl the bar up toward the shoulders, then lower until the arms are fully straight.",
      joint_path: "Elbows flex and extend in place; the upper arms stay pinned.",
      range_of_motion: "Full extension at the bottom and bar at shoulder height at the top.",
      tempo_and_control: "Two seconds up, three seconds down.",
      breathing: "Exhale as you curl, inhale as you lower.",
      end_position: "Bar at the shoulders with the elbows still beside the ribs.",
      common_mistakes: "Stepping back to cheat the bottom, and letting the elbows drift forward.",
      coaching_cues: ["Stand tall", "Reach full straight arms", "Squeeze at the top"],
      intended_target: "Biceps volume with continuous cable tension and easy load adjustment.",
      safety_notes: "Use the machine's weight horn as a spotter when working near the stack.",
    },
  },
  {
    slug: "close_grip_bench_press",
    name: "Close-grip bench press",
    aliases: ["close grip press", "narrow grip bench"],
    variationKey: "bench_press:close_grip",
    variationLabel: "Close grip, shoulder-width hands",
    category: "compound",
    movementPattern: "horizontal_push",
    primaryMovementFunction: "horizontal_press",
    movementFunctions: ["horizontal_press", "elbow_extension"],
    roles: ["compound_movement", "hypertrophy_movement", "lengthened_position_emphasis"],
    equipment: ["barbell", "adjustable_bench"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Horizontal press with the hands close together; triceps leaning with a chest contribution.",
    relations: [
      { muscle: "triceps_brachii", role: "primary_mover", weight: 0.65, confidence: 0.8 },
      { muscle: "pectoralis_major", role: "secondary_mover", weight: 0.5, confidence: 0.8 },
      { muscle: "deltoid_front", role: "secondary_mover", weight: 0.25, confidence: 0.75 },
    ],
    structureRelations: [
      {
        muscle: "triceps_brachii",
        structure: "lateral_head",
        role: "primary_mover",
        weight: 0.3,
        emphasis: "structure_biased",
        confidence: 0.7,
      },
      {
        muscle: "triceps_brachii",
        structure: "medial_head",
        role: "primary_mover",
        weight: 0.2,
        emphasis: "structure_biased",
        confidence: 0.65,
        notes: "Medial head contribution; never claimed to be isolated by grip width.",
      },
    ],
    form: {
      setup: "Lie on a flat bench and grip the barbell just outside shoulder width.",
      body_position: "Feet planted, upper back set on the bench.",
      grip: "Close overhand grip, hands no wider than the shoulders.",
      start_position: "Bar resting over the lower chest with the elbows near the torso.",
      movement_path: "Lower the bar to the lower chest, keeping the elbows close, then press it up.",
      joint_path: "Elbows extend along a path that stays nearer the ribs than a normal press.",
      range_of_motion: "Lower until the bar touches the lower chest without losing the shoulder-blade set.",
      tempo_and_control: "Control the descent and press without bouncing.",
      breathing: "Inhale down, exhale up.",
      end_position: "Arms extended above the chest.",
      common_mistakes: "Letting the hands drift shoulder-width apart, bouncing the bar, and flaring the elbows.",
      coaching_cues: ["Hands stay close", "Elbows by your sides", "Controlled descent"],
      intended_target: "Triceps pressing volume with chest and front-deltoid contribution.",
      safety_notes: "Grip too narrow and the wrists take the load; shoulder width is the practical limit.",
    },
  },
  {
    slug: "skull_crusher_ez_bar",
    name: "EZ-bar skull crusher",
    aliases: ["skull crusher", "lying triceps extension", "EZ bar lying extension"],
    variationKey: "triceps_extension:lying_ez",
    variationLabel: "Lying, EZ bar",
    category: "isolation",
    primaryMovementFunction: "elbow_extension",
    movementFunctions: ["elbow_extension"],
    roles: ["isolation_movement", "lengthened_position_emphasis", "hypertrophy_movement"],
    equipment: ["ez_bar", "adjustable_bench"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_single_joint",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Lying elbow extension with the shoulder slightly flexed; biases the triceps long head.",
    relations: [
      {
        muscle: "triceps_brachii",
        role: "primary_mover",
        weight: 0.85,
        emphasis: "lengthened_position",
        confidence: 0.8,
      },
    ],
    structureRelations: [
      {
        muscle: "triceps_brachii",
        structure: "long_head",
        role: "primary_mover",
        weight: 0.45,
        emphasis: "lengthened_position",
        confidence: 0.8,
        notes:
          "The shoulder flexion of a lying extension lengthens the long head at the bottom. Bias, not isolation.",
      },
      {
        muscle: "triceps_brachii",
        structure: "lateral_head",
        role: "secondary_mover",
        weight: 0.3,
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Lie on a flat bench holding an EZ bar with a shoulder-width grip.",
      body_position: "Back flat, feet planted, upper arms pointing at the ceiling and slightly toward the head.",
      grip: "Overhand grip on the EZ bar.",
      start_position: "Arms extended with the bar above the chest.",
      movement_path: "Bend the elbows to lower the bar toward the forehead, then extend back up.",
      joint_path: "Only the elbows move; the upper arms stay angled back and fixed.",
      range_of_motion: "Lower until the bar reaches just in front of the forehead without the arms touching.",
      tempo_and_control: "Three seconds down, one second up; do not drop behind the head.",
      breathing: "Inhale on the way down, exhale as you extend.",
      end_position: "Arms extended above the chest with the upper arms still angled back.",
      common_mistakes: "Dropping the bar behind the head, flaring the elbows out to the sides, and moving the shoulders.",
      coaching_cues: ["Elbows point at the ceiling", "Lower to the forehead, not the head", "Upper arms stay put"],
      intended_target: "Triceps long-head-biased extension work at a lengthened bottom position.",
      safety_notes: "The bar must not travel behind the head; keep the upper arms angled back and stop at the forehead.",
    },
  },
  {
    slug: "overhead_cable_extension",
    name: "Overhead cable triceps extension",
    aliases: ["overhead triceps extension", "rope overhead extension"],
    variationKey: "triceps_extension:overhead_rope",
    variationLabel: "Overhead, rope",
    category: "isolation",
    primaryMovementFunction: "elbow_extension",
    movementFunctions: ["elbow_extension", "shoulder_extension"],
    roles: ["isolation_movement", "lengthened_position_emphasis", "hypertrophy_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Full overhead extension; the strongest long-head bias in the catalog.",
    relations: [
      {
        muscle: "triceps_brachii",
        role: "primary_mover",
        weight: 0.85,
        emphasis: "lengthened_position",
        confidence: 0.85,
      },
    ],
    structureRelations: [
      {
        muscle: "triceps_brachii",
        structure: "long_head",
        role: "primary_mover",
        weight: 0.55,
        emphasis: "lengthened_position",
        confidence: 0.85,
        notes:
          "Full shoulder extension plus elbow extension places the long head at its longest. This is the clearest long-head-biased movement FitCoach catalogues, and it is still not isolation.",
      },
      {
        muscle: "triceps_brachii",
        structure: "lateral_head",
        role: "secondary_mover",
        weight: 0.25,
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Attach a rope to a high pulley and step forward until the cable is taut overhead.",
      body_position: "Feet staggered, knees soft, torso upright, ribs down.",
      grip: "Two-handed rope grip with the palms facing each other.",
      start_position: "Arms extended overhead with the upper arms beside the ears.",
      movement_path: "Bend the elbows to lower the rope behind the head, then extend back overhead.",
      joint_path: "Elbows stay pointing forward and fixed; the forearms move through the arc.",
      range_of_motion: "Lower until you feel a strong stretch in the triceps with the upper arms still beside the ears.",
      tempo_and_control: "Three seconds down, one second up.",
      breathing: "Inhale as the rope lowers, exhale as you extend.",
      end_position: "Arms fully extended overhead.",
      common_mistakes: "Letting the elbows flare outward, arching the lower back, and going too heavy to control the bottom.",
      coaching_cues: ["Upper arms stay beside the ears", "Elbows forward, not out", "Own the stretch"],
      intended_target: "Triceps long head worked from a deeply lengthened position.",
      safety_notes: "Keep the ribs down; arching to reach the bottom turns this into a lower-back exercise.",
    },
  },
  {
    slug: "cable_triceps_pushdown",
    name: "Cable triceps pushdown",
    aliases: ["triceps pushdown", "rope pushdown", "pushdown"],
    variationKey: "triceps_pushdown:rope_high",
    variationLabel: "High pulley, rope",
    category: "isolation",
    primaryMovementFunction: "elbow_extension",
    movementFunctions: ["elbow_extension", "forearm_pronation"],
    roles: ["isolation_movement", "shortened_position_emphasis", "hypertrophy_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "shortened_emphasised",
    summary: "Standing elbow extension; the complement to overhead extension, anchoring the work at full contraction.",
    relations: [
      {
        muscle: "triceps_brachii",
        role: "primary_mover",
        weight: 0.8,
        emphasis: "shortened_position",
        confidence: 0.85,
      },
    ],
    structureRelations: [
      {
        muscle: "triceps_brachii",
        structure: "lateral_head",
        role: "primary_mover",
        weight: 0.4,
        emphasis: "structure_biased",
        confidence: 0.75,
        notes:
          "An upright, shoulder-neutral pushdown places more of the work on the lateral head than an overhead extension does. Contribution, not isolation.",
      },
      {
        muscle: "triceps_brachii",
        structure: "long_head",
        role: "secondary_mover",
        weight: 0.3,
        emphasis: "shortened_position",
        confidence: 0.75,
      },
    ],
    form: {
      setup: "Attach a rope to a high pulley and stand facing away from the machine.",
      body_position: "Feet hip-width, knees softly bent, torso upright with a slight forward lean.",
      grip: "Rope grip with palms facing each other at chest height.",
      start_position: "Elbows bent about 90° with the upper arms beside the ribs.",
      movement_path: "Extend the elbows to press the rope down to the thighs, then let it rise under control.",
      joint_path: "Elbows stay pinned to the sides; the forearms rotate slightly as the rope is split at the bottom.",
      range_of_motion: "Extend fully at the bottom and return until the elbows are about 90°.",
      tempo_and_control: "Two seconds down, three seconds up.",
      breathing: "Exhale as you press down, inhale on the return.",
      end_position: "Arms straight beside the thighs with the rope squeezed.",
      common_mistakes: "Letting the upper arms flare and turning it into a pressdown with the shoulders.",
      coaching_cues: ["Elbows glued to your sides", "Full lockout at the bottom", "Slow return"],
      intended_target: "Triceps extension anchored at full contraction, with a lateral-head lean.",
      safety_notes: "Use a lighter weight than you think you need; the elbows drifting is the usual failure.",
    },
  },
];
