import type { KnowledgeExercise } from "./knowledgeTypes";

/**
 * PHASE 2 KNOWLEDGE FIXTURES — legs and core.
 *
 * Leg work is separated by joint action (squat, hinge, knee extension, knee
 * flexion, hip extension, hip abduction, calf raising) rather than by region
 * name, because that is the axis a planner actually composes against. Core
 * work is classified by what it resists (anti-extension, anti-rotation) rather
 * than by "ab exercise".
 */

export const LEG_AND_CORE_EXERCISES: readonly KnowledgeExercise[] = [
  {
    slug: "barbell_back_squat",
    name: "Barbell back squat",
    aliases: ["back squat", "squat", "barbell squat"],
    variationKey: "back_squat:barbell_high_bar",
    variationLabel: "Barbell, high bar",
    category: "compound",
    movementPattern: "squat",
    primaryMovementFunction: "squat",
    movementFunctions: ["squat", "knee_extension", "hip_extension"],
    roles: ["compound_movement", "primary_strength_movement", "hypertrophy_movement"],
    equipment: ["barbell", "squat_rack"],
    stabilityDemand: "high",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "The primary lower-body strength movement; quadriceps and glutes with spinal support.",
    relations: [
      { muscle: "quadriceps", role: "primary_mover", weight: 0.8, confidence: 0.85 },
      { muscle: "gluteus_maximus", role: "primary_mover", weight: 0.7, confidence: 0.85 },
      { muscle: "hamstrings", role: "secondary_mover", weight: 0.3, confidence: 0.75 },
      { muscle: "adductor_group", role: "supporting", weight: 0.25, confidence: 0.75 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.4, confidence: 0.85 },
      { muscle: "gluteus_medius", role: "stabilizer", weight: 0.2, confidence: 0.7 },
    ],
    structureRelations: [
      {
        muscle: "quadriceps",
        structure: "vastus_lateralis",
        role: "primary_mover",
        weight: 0.35,
        emphasis: "structure_biased",
        confidence: 0.75,
      },
      {
        muscle: "quadriceps",
        structure: "vastus_medialis",
        role: "primary_mover",
        weight: 0.2,
        confidence: 0.75,
      },
      {
        muscle: "quadriceps",
        structure: "rectus_femoris",
        role: "secondary_mover",
        weight: 0.15,
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Set the bar in the rack, unrack it, and walk back two steps with the bar across the upper traps.",
      body_position: "Feet shoulder-width with toes slightly out, chest up, core braced.",
      grip: "Bar across the rear delts/upper traps, hands just outside shoulder width.",
      start_position: "Standing tall with the weight balanced over the mid-foot.",
      movement_path: "Sit down and back between the hips until at least parallel, then drive up through the whole foot.",
      joint_path: "Knees track in line with the toes; hips travel back as the knees flex.",
      range_of_motion: "Descend to at least hip-parallel, deeper if the ankles and hips allow it cleanly.",
      tempo_and_control: "Controlled descent for about two seconds, no bouncing out of the bottom.",
      breathing: "Take a big breath before the descent, exhale as you stand up.",
      end_position: "Fully upright with the hips extended and the bar still balanced.",
      common_mistakes: "Knees collapsing inward, heels lifting, and the hips shooting up at the start of the ascent.",
      coaching_cues: ["Spread the floor", "Chest and hips rise together", "Knees follow the toes"],
      intended_target: "Whole lower-body strength with quads and glutes as the main drivers.",
      safety_notes: "Use safeties and never squat alone to a maximal single; a stuck squat is dangerous, not impressive.",
    },
  },
  {
    slug: "goblet_front_squat",
    name: "Goblet squat",
    aliases: ["goblet squat", "front squat", "kettlebell front squat"],
    variationKey: "front_squat:goblet_kettlebell",
    variationLabel: "Goblet hold, kettlebell",
    category: "compound",
    movementPattern: "squat",
    primaryMovementFunction: "squat",
    movementFunctions: ["squat", "knee_extension", "hip_extension"],
    roles: ["compound_movement", "hypertrophy_movement", "accessory_movement"],
    equipment: ["kettlebell", "dumbbells"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Front-loaded squat variation; an upright torso makes quad depth the limiting factor.",
    relations: [
      { muscle: "quadriceps", role: "primary_mover", weight: 0.75, confidence: 0.8 },
      { muscle: "gluteus_maximus", role: "primary_mover", weight: 0.55, confidence: 0.8 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.35, confidence: 0.8 },
    ],
    form: {
      setup: "Hold a kettlebell by the horns at chest height, elbows tucked underneath.",
      body_position: "Feet shoulder-width, chest tall, elbows pointing down and forward.",
      grip: "Both hands on the kettlebell horns close to the chest.",
      start_position: "Standing with the weight racked at the chest.",
      movement_path: "Sit down between the hips and stand back up, keeping the elbows under the knees.",
      joint_path: "Knees flex and track over the toes; the torso stays upright.",
      range_of_motion: "Descend until the hamstrings are stretched and the hips pass below the top of the knee.",
      tempo_and_control: "Smooth descent, then a decisive stand-up.",
      breathing: "Inhale at the top, exhale through the hardest part of the ascent.",
      end_position: "Standing tall with the weight still racked at the chest.",
      common_mistakes: "Letting the elbows flare, leaning forward, and losing the upright torso.",
      coaching_cues: ["Elbows under the knees", "Chest tall", "Stand up with the hips"],
      intended_target: "Quadriceps depth and trunk position, without the bar-on-the-back setup.",
      safety_notes: "Front-loaded squats stress the lower back position; keep the load light enough to hold the chest up.",
    },
  },
  {
    slug: "leg_press",
    name: "Leg press",
    aliases: ["leg press machine", "machine leg press"],
    variationKey: "leg_press:seated_platform",
    variationLabel: "Seated, shoulder-width platform",
    category: "compound",
    movementPattern: "squat",
    primaryMovementFunction: "squat",
    movementFunctions: ["squat", "knee_extension", "hip_extension"],
    roles: ["compound_movement", "hypertrophy_movement", "accessory_movement"],
    equipment: ["leg_press"],
    stabilityDemand: "low",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "partial_rom",
    summary: "Guided knee-extension loading; high quad volume without balance or barbell demand.",
    relations: [
      { muscle: "quadriceps", role: "primary_mover", weight: 0.75, confidence: 0.85 },
      { muscle: "gluteus_maximus", role: "secondary_mover", weight: 0.4, confidence: 0.8 },
      { muscle: "adductor_group", role: "supporting", weight: 0.2, confidence: 0.7 },
      { muscle: "hamstrings", role: "supporting", weight: 0.15, confidence: 0.7 },
    ],
    form: {
      setup: "Sit fully back into the seat with the whole back and head against the pad.",
      body_position: "Lower back pinned to the pad, feet shoulder-width on the platform.",
      grip: "Hands holding the side handles.",
      start_position: "Knees bent to about 90° with the hips and lower back flat on the pad.",
      movement_path: "Extend the knees to press the platform away, then lower until the knees bend again.",
      joint_path: "Knees extend and flex evenly; the hips stay on the pad.",
      range_of_motion: "Lower until the hips begin to lift off the pad, and no further.",
      tempo_and_control: "Control the descent; do not let the knees ride over the toes.",
      breathing: "Inhale on the descent, exhale as you press.",
      end_position: "Legs extended but not locked, with the lower back still on the pad.",
      common_mistakes: "Letting the lower back arch off the pad at the bottom, and locking the knees at the top.",
      coaching_cues: ["Back glued to the pad", "Whole foot on the plate", "Stop before the hips lift"],
      intended_target: "Quadriceps volume with very little stabilisation demand.",
      safety_notes: "Never lock the knees at full extension; the hyperextended knee position is where press injuries start.",
    },
  },
  {
    slug: "romanian_deadlift",
    name: "Romanian deadlift",
    aliases: ["RDL", "romanian deadlift", "stiff leg deadlift"],
    variationKey: "romanian_deadlift:barbell",
    variationLabel: "Barbell, hip-hinge",
    category: "compound",
    movementPattern: "hinge",
    primaryMovementFunction: "hinge",
    movementFunctions: ["hinge", "hip_extension", "knee_flexion"],
    roles: ["compound_movement", "hamstring_knee_flexion", "hypertrophy_movement", "lengthened_position_emphasis"],
    equipment: ["barbell"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "stretch_emphasised",
    summary: "Hip hinge that loads the hamstrings long; the go-to posterior-chain movement.",
    relations: [
      {
        muscle: "hamstrings",
        role: "primary_mover",
        weight: 0.8,
        emphasis: "lengthened_position",
        confidence: 0.85,
      },
      { muscle: "gluteus_maximus", role: "primary_mover", weight: 0.65, confidence: 0.85 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.4, confidence: 0.85 },
      { muscle: "adductor_group", role: "supporting", weight: 0.2, confidence: 0.7 },
      { muscle: "forearm_flexors", role: "supporting", weight: 0.25, confidence: 0.8 },
    ],
    structureRelations: [
      {
        muscle: "hamstrings",
        structure: "biceps_femoris",
        role: "primary_mover",
        weight: 0.3,
        emphasis: "structure_biased",
        confidence: 0.7,
      },
      {
        muscle: "hamstrings",
        structure: "semimembranosus",
        role: "secondary_mover",
        weight: 0.25,
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Hold the barbell at hip height with an overhand grip just outside the thighs.",
      body_position: "Feet hip-width, knees softly bent and staying that way, back flat and chest up.",
      grip: "Overhand grip just outside the thighs.",
      start_position: "Standing tall with the bar resting against the upper thighs.",
      movement_path: "Push the hips back and lower the bar down the legs, then drive the hips forward to stand.",
      joint_path: "Hip extension with a small, constant knee bend; the spine angle changes but the back stays flat.",
      range_of_motion: "Lower until you feel a strong hamstring stretch — typically just below the knee.",
      tempo_and_control: "Three seconds down, driving up with the glutes.",
      breathing: "Inhale at the top, exhale on the way up.",
      end_position: "Standing tall with the bar back against the thighs.",
      common_mistakes: "Rounding the back, turning it into a squat, and bending the knees more on the way down.",
      coaching_cues: ["Hips back, bar down the legs", "Back stays flat", "Stand up by driving the hips forward"],
      intended_target: "Hamstrings and glutes from a lengthened position.",
      safety_notes: "Stop the descent the moment the back starts to round; the load is then too heavy for the position.",
    },
  },
  {
    slug: "leg_extension",
    name: "Leg extension",
    aliases: ["leg extension machine", "knee extension"],
    variationKey: "leg_extension:seated",
    variationLabel: "Seated machine",
    category: "isolation",
    movementPattern: "other",
    primaryMovementFunction: "knee_extension",
    movementFunctions: ["knee_extension"],
    roles: ["isolation_movement", "knee_extension_movement", "shortened_position_emphasis", "hypertrophy_movement"],
    equipment: ["leg_extension_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "shortened_emphasised",
    summary: "Seated knee extension; direct quadriceps work at full contraction.",
    relations: [
      {
        muscle: "quadriceps",
        role: "primary_mover",
        weight: 0.85,
        emphasis: "shortened_position",
        confidence: 0.85,
      },
    ],
    structureRelations: [
      {
        muscle: "quadriceps",
        structure: "vastus_lateralis",
        role: "primary_mover",
        weight: 0.3,
        emphasis: "structure_biased",
        confidence: 0.7,
      },
      {
        muscle: "quadriceps",
        structure: "rectus_femoris",
        role: "secondary_mover",
        weight: 0.15,
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Adjust the seat so the knee pivot lines up with the machine's axle.",
      body_position: "Back and hips pressed into the seat, knees slightly in front of the hips.",
      grip: "Hands holding the thigh pad down or the side handles.",
      start_position: "Knees bent with the pad resting on the shins just above the ankles.",
      movement_path: "Extend the knees to lift the pad to full contraction, then lower slowly.",
      joint_path: "Only the knees extend; the hips stay anchored in the seat.",
      range_of_motion: "Extend until the legs are nearly straight, without locking the knees hard.",
      tempo_and_control: "Two seconds up, three seconds down.",
      breathing: "Exhale as you extend, inhale on the return.",
      end_position: "Legs extended with the quadriceps squeezed.",
      common_mistakes: "Kicking through the momentum, hyperextending the knees at the top, and lifting the hips.",
      coaching_cues: ["Pin the hips down", "Lift with the quads", "Slow negative"],
      intended_target: "Quadriceps contraction at the shortened position of the knee.",
      safety_notes: "Stop before the knees lock; the machine's leverage at full extension is highest there.",
    },
  },
  {
    slug: "lying_leg_curl",
    name: "Lying leg curl",
    aliases: ["leg curl", "hamstring curl machine", "prone leg curl"],
    variationKey: "leg_curl:prone",
    variationLabel: "Prone, ankle pad",
    category: "isolation",
    movementPattern: "hinge",
    primaryMovementFunction: "knee_flexion",
    movementFunctions: ["knee_flexion"],
    roles: ["isolation_movement", "hamstring_knee_flexion", "hypertrophy_movement"],
    equipment: ["leg_curl_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "partial_rom",
    summary: "Prone knee flexion; the direct hamstring isolation movement.",
    relations: [
      { muscle: "hamstrings", role: "primary_mover", weight: 0.85, confidence: 0.85 },
      { muscle: "gastrocnemius", role: "supporting", weight: 0.1, confidence: 0.65 },
    ],
    structureRelations: [
      {
        muscle: "hamstrings",
        structure: "biceps_femoris",
        role: "primary_mover",
        weight: 0.3,
        emphasis: "structure_biased",
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Lie face down with the ankle pad just above the heels and adjust the height so the hips stay down.",
      body_position: "Hips and abdomen pressed into the pad, legs extending straight in front.",
      grip: "Hands holding the front handles.",
      start_position: "Legs extended with the pad resting above the heels.",
      movement_path: "Curl the heels toward the glutes, then lower the weight slowly.",
      joint_path: "Knees flex; the hips must not lift off the pad.",
      range_of_motion: "Curl until the heels approach the glutes without lifting the hips.",
      tempo_and_control: "Two seconds up, three seconds down.",
      breathing: "Exhale as you curl, inhale on the return.",
      end_position: "Heels near the glutes, hips still down.",
      common_mistakes: "Lifting the hips to cheat the weight up, and using momentum.",
      coaching_cues: ["Hips stay glued down", "Curl the heels to the glutes"],
      intended_target: "Hamstrings through knee flexion.",
      safety_notes: "Use the return slowly; dropping the pad onto the shins is the most common avoidable injury on this machine.",
    },
  },
  {
    slug: "hip_thrust",
    name: "Hip thrust",
    aliases: ["glute bridge", "barbell hip thrust"],
    variationKey: "hip_thrust:barbell",
    variationLabel: "Barbell, shoulder-blade supported",
    category: "isolation",
    movementPattern: "hinge",
    primaryMovementFunction: "hip_extension",
    movementFunctions: ["hip_extension"],
    roles: ["isolation_movement", "hypertrophy_movement", "lengthened_position_emphasis"],
    equipment: ["barbell", "adjustable_bench"],
    stabilityDemand: "low",
    loadingCharacteristic: "free_weight_multi_joint",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Loaded hip extension with the torso supported; heavy gluteus maximus work at full contraction.",
    relations: [
      { muscle: "gluteus_maximus", role: "primary_mover", weight: 0.9, emphasis: "shortened_position", confidence: 0.85 },
      { muscle: "hamstrings", role: "secondary_mover", weight: 0.25, confidence: 0.75 },
      { muscle: "adductor_group", role: "supporting", weight: 0.15, confidence: 0.7 },
    ],
    form: {
      setup: "Sit with the upper back against a bench, the bar over the hips, and the feet planted.",
      body_position: "Chin tucked, ribs down, knees bent about 90° and pointing forward.",
      grip: "Hands holding the bar at the hips or braced on the bench behind you.",
      start_position: "Upper back on the bench, chin tucked, hips low near the floor.",
      movement_path: "Drive the hips up until the torso and thighs form a straight line, then lower under control.",
      joint_path: "Hip extension only; the chin stays tucked so the lumbar spine does not arch.",
      range_of_motion: "Lock out at the top with the ribs down, lower until the hips feel the stretch.",
      tempo_and_control: "One second up with a hard squeeze, three seconds down.",
      breathing: "Exhale as you drive up, inhale as you lower.",
      end_position: "Hips level with the shoulders, glutes fully squeezed, ribs down.",
      common_mistakes: "Overarching the lower back at the top and hyperextending the neck.",
      coaching_cues: ["Tuck the chin", "Ribs down", "Squeeze the glutes at the top"],
      intended_target: "Gluteus maximus at full hip extension.",
      safety_notes: "Pad the bar; never perform this with the lumbar spine arched into extension.",
    },
  },
  {
    slug: "hip_abduction_machine",
    name: "Seated hip abduction",
    aliases: ["abduction machine", "seated leg raise", "hip abduction"],
    variationKey: "hip_abduction:seated",
    variationLabel: "Seated machine",
    category: "isolation",
    movementPattern: "other",
    primaryMovementFunction: "hip_abduction",
    movementFunctions: ["hip_abduction"],
    roles: ["isolation_movement", "hip_abduction_movement", "hypertrophy_movement"],
    equipment: ["hip_abduction_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Seated hip abduction for the gluteus medius and minimus.",
    relations: [
      { muscle: "gluteus_medius", role: "primary_mover", weight: 0.85, confidence: 0.8 },
      { muscle: "gluteus_minimus", role: "secondary_mover", weight: 0.45, confidence: 0.75 },
      { muscle: "gluteus_maximus", role: "supporting", weight: 0.15, confidence: 0.7 },
    ],
    form: {
      setup: "Sit with the back against the pad and the knees positioned against the lower pads.",
      body_position: "Torso upright and leaning back against the seat, feet flat on the footrests.",
      grip: "Hands holding the handles beside the seat.",
      start_position: "Legs together with the knees against the pads.",
      movement_path: "Push the knees apart against the pads, then return until they nearly touch.",
      joint_path: "Hip abduction with the knees staying level; no leaning side to side.",
      range_of_motion: "Return until the legs are close together without letting them slam shut.",
      tempo_and_control: "Two seconds out, three seconds back.",
      breathing: "Exhale as the legs open, inhale as they return.",
      end_position: "Legs apart with the glutes engaged.",
      common_mistakes: "Leaning back or sideways to move the weight, and swinging the return.",
      coaching_cues: ["Chest tall", "Lead with the knees", "Control the return"],
      intended_target: "Hip abductor strength, relevant for knee tracking and pelvis control.",
      safety_notes: "Keep the knees tracking over the feet; abduction with the feet rotating externally stresses the hip.",
    },
  },
  {
    slug: "standing_calf_raise",
    name: "Standing calf raise",
    aliases: ["calf raise", "standing calf raise"],
    variationKey: "calf_raise:standing",
    variationLabel: "Standing, full range",
    category: "isolation",
    movementPattern: "other",
    primaryMovementFunction: "plantarflexion",
    movementFunctions: ["plantarflexion"],
    roles: ["isolation_movement", "calf_raising", "hypertrophy_movement"],
    equipment: ["bodyweight", "dumbbells"],
    stabilityDemand: "moderate",
    loadingCharacteristic: "bodyweight_external_load",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Standing plantarflexion; biases the gastrocnemius, which crosses the knee.",
    relations: [
      { muscle: "gastrocnemius", role: "primary_mover", weight: 0.85, confidence: 0.85 },
      { muscle: "soleus", role: "secondary_mover", weight: 0.45, confidence: 0.8 },
    ],
    structureRelations: [
      {
        muscle: "gastrocnemius",
        structure: "medial_head",
        role: "primary_mover",
        weight: 0.3,
        emphasis: "structure_biased",
        confidence: 0.7,
      },
      {
        muscle: "gastrocnemius",
        structure: "lateral_head",
        role: "primary_mover",
        weight: 0.25,
        emphasis: "structure_biased",
        confidence: 0.7,
      },
    ],
    form: {
      setup: "Stand with the balls of the feet on the edge of a step or on flat ground.",
      body_position: "Feet hip-width, knees straight but not locked, weight over the balls of the feet.",
      grip: "Fingertips on a wall or rail for balance only.",
      start_position: "Heels low with a full stretch in the calves.",
      movement_path: "Rise onto the balls of the feet as high as possible, then lower the heels slowly.",
      joint_path: "Ankle plantarflexion with the knees straight so the gastrocnemius does the work.",
      range_of_motion: "Full stretch at the bottom and a hard squeeze at the top; pause at both ends.",
      tempo_and_control: "Two seconds down, one second up, with a pause at the bottom.",
      breathing: "Exhale as you rise, inhale as you lower.",
      end_position: "Standing tall on the balls of the feet with the calves squeezed.",
      common_mistakes: "Bouncing out of the bottom, cutting the stretch, and using the hands for momentum.",
      coaching_cues: ["Slow and low", "Pause at the bottom", "Full squeeze at the top"],
      intended_target: "Gastrocnemius development with a smaller soleus contribution.",
      safety_notes: "Use a step only if you can control the descent fully; bouncing off a step is a way to injure the achilles.",
    },
  },
  {
    slug: "seated_calf_raise",
    name: "Seated calf raise",
    aliases: ["seated calf raise", "machine calf raise"],
    variationKey: "calf_raise:seated",
    variationLabel: "Seated, knee bent",
    category: "isolation",
    movementPattern: "other",
    primaryMovementFunction: "plantarflexion",
    movementFunctions: ["plantarflexion"],
    roles: ["isolation_movement", "calf_raising", "hypertrophy_movement"],
    equipment: ["calf_raise_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "machine_guided",
    rangeOfMotionCharacteristic: "full_stretch_to_squeeze",
    summary: "Seated plantarflexion with the knee bent; biases the soleus.",
    relations: [
      { muscle: "soleus", role: "primary_mover", weight: 0.85, confidence: 0.85 },
      { muscle: "gastrocnemius", role: "secondary_mover", weight: 0.3, confidence: 0.8 },
    ],
    form: {
      setup: "Sit with the pad resting on the lower shins just above the ankles and set the weight.",
      body_position: "Back against the seat, knees bent to about 90°, feet flat on the footplate.",
      grip: "Hands holding the thigh pad down lightly.",
      start_position: "Heels as low as they will go with the toes pointing down.",
      movement_path: "Press up onto the balls of the feet, then lower the heels slowly.",
      joint_path: "Ankle plantarflexion with the knee flexed so the gastrocnemius is shortened out of the movement.",
      range_of_motion: "Full stretch at the bottom, hard squeeze at the top.",
      tempo_and_control: "Two seconds down, one second up, pausing at both ends.",
      breathing: "Exhale as you press up, inhale as you lower.",
      end_position: "Up on the balls of the feet with the calves squeezed.",
      common_mistakes: "Fast partials, and resting the weight on the pad between reps.",
      coaching_cues: ["Slow stretch at the bottom", "Pause at the top", "Toes straight"],
      intended_target: "Soleus development and lower-calf balance.",
      safety_notes: "Control the descent; the loaded stretch at the bottom is where the risk sits.",
    },
  },
  {
    slug: "plank",
    name: "Plank",
    aliases: ["front plank", "forearm plank"],
    variationKey: "plank:forearm",
    variationLabel: "Forearm plank",
    category: "isolation",
    movementPattern: "core",
    primaryMovementFunction: "anti_extension",
    movementFunctions: ["anti_extension"],
    roles: ["isolation_movement", "core_anti_extension", "accessory_movement"],
    equipment: ["bodyweight"],
    stabilityDemand: "high",
    loadingCharacteristic: "bodyweight_only",
    rangeOfMotionCharacteristic: "partial_rom",
    summary: "Isometric anti-extension; teaches the trunk to resist sagging under load.",
    relations: [
      { muscle: "transversus_abdominis", role: "primary_mover", weight: 0.7, confidence: 0.8 },
      { muscle: "rectus_abdominis", role: "secondary_mover", weight: 0.4, confidence: 0.8 },
      { muscle: "obliques", role: "supporting", weight: 0.3, confidence: 0.75 },
      { muscle: "erector_spinae", role: "stabilizer", weight: 0.25, confidence: 0.75 },
    ],
    form: {
      setup: "Set the forearms on the floor with the elbows under the shoulders.",
      body_position: "One straight line from head to heels, glutes and ribs gently set.",
      grip: "Forearms on the floor with the hands flat and elbows under the shoulders.",
      start_position: "On the forearms with the body in a straight line.",
      movement_path: "Hold the position, squeezing the glutes and abdomen and keeping the hips level.",
      joint_path: "No movement of the hips; the trunk resists extension rather than creating it.",
      range_of_motion: "Hold as long as the position stays clean; stop when the hips start to sag or pike.",
      tempo_and_control: "Isometric; keep breathing throughout.",
      breathing: "Shallow, continuous breathing — never hold the breath to extend the hold.",
      end_position: "Still level from shoulders to heels.",
      common_mistakes: "Hips sagging or piking, and holding the breath.",
      coaching_cues: ["Squeeze the glutes", "Ribs down", "Long neck"],
      intended_target: "Trunk stiffness under an anti-extension demand.",
      safety_notes: "Shorter, cleaner holds beat long, collapsed ones; stop the set when the position fails.",
    },
  },
  {
    slug: "dead_bug",
    name: "Dead bug",
    aliases: ["dead bug", "supine dead bug"],
    variationKey: "dead_bug:supine",
    variationLabel: "Supine, opposite arm and leg",
    category: "isolation",
    movementPattern: "core",
    primaryMovementFunction: "anti_extension",
    movementFunctions: ["anti_extension"],
    roles: ["isolation_movement", "core_anti_extension", "accessory_movement"],
    equipment: ["bodyweight"],
    stabilityDemand: "low",
    loadingCharacteristic: "bodyweight_only",
    rangeOfMotionCharacteristic: "partial_rom",
    summary: "Supine anti-extension with limbs moving; gentler and more usable than a plank.",
    relations: [
      { muscle: "transversus_abdominis", role: "primary_mover", weight: 0.75, confidence: 0.8 },
      { muscle: "rectus_abdominis", role: "secondary_mover", weight: 0.45, confidence: 0.8 },
      { muscle: "obliques", role: "supporting", weight: 0.3, confidence: 0.75 },
    ],
    form: {
      setup: "Lie on your back with the hips and knees bent to 90° and the arms pointing at the ceiling.",
      body_position: "Lower back gently pressed into the floor, ribs down.",
      grip: "Arms reaching toward the ceiling, palms facing the feet.",
      start_position: "On the back with the table-top position held and the lower back flat.",
      movement_path: "Lower the opposite arm and leg toward the floor, then return to the start.",
      joint_path: "Hip and shoulder move; the spine stays in the same position throughout.",
      range_of_motion: "Lower the limbs only as far as the lower back stays flat on the floor.",
      tempo_and_control: "Slow, controlled, one rep per 3–4 seconds.",
      breathing: "Exhale as the limbs extend, inhale as they return.",
      end_position: "Back in the table-top position with the lower back still flat.",
      common_mistakes: "Letting the lower back arch off the floor as the limbs extend.",
      coaching_cues: ["Keep the low back glued down", "Short range is fine", "Slow and controlled"],
      intended_target: "Anti-extension trunk control that is easy to scale and joint-friendly.",
      safety_notes: "Reduce the range of limb travel before you reduce the quality of the position.",
    },
  },
  {
    slug: "pallof_press",
    name: "Pallof press",
    aliases: ["pallof press", "cable anti rotation press"],
    variationKey: "pallof_press:cable",
    variationLabel: "Cable, standing, half-kneeling",
    category: "isolation",
    movementPattern: "rotation",
    primaryMovementFunction: "anti_rotation",
    movementFunctions: ["anti_rotation"],
    roles: ["isolation_movement", "core_rotation", "accessory_movement"],
    equipment: ["cable_machine"],
    stabilityDemand: "low",
    loadingCharacteristic: "cable_variable",
    rangeOfMotionCharacteristic: "partial_rom",
    summary: "Resist trunk rotation under lateral load; the practical anti-rotation press.",
    relations: [
      { muscle: "obliques", role: "primary_mover", weight: 0.7, confidence: 0.8 },
      { muscle: "transversus_abdominis", role: "primary_mover", weight: 0.55, confidence: 0.8 },
      { muscle: "rectus_abdominis", role: "supporting", weight: 0.2, confidence: 0.7 },
    ],
    form: {
      setup: "Set a cable at chest height and stand several feet away holding the handle with both hands.",
      body_position: "Feet staggered, knees soft, torso square to the cable line.",
      grip: "Both hands on a single handle, arms extended at chest height.",
      start_position: "Arms extended forward with the ribs down and the shoulders level.",
      movement_path: "Press the handle away from the body until the arms are extended, then return under control.",
      joint_path: "Only the elbows bend; the torso does not rotate at all.",
      range_of_motion: "Press until the arms are straight, then return to the start position.",
      tempo_and_control: "Two seconds out, three seconds back, no torso rotation at any point.",
      breathing: "Exhale as you press, inhale as you return.",
      end_position: "Arms extended forward, torso square.",
      common_mistakes: "Letting the hips or shoulders rotate toward the cable.",
      coaching_cues: ["Square to the front", "Press away, don't pull", "No rotation"],
      intended_target: "Anti-rotation trunk strength under an external load.",
      safety_notes: "Start lighter than necessary; the point is a still torso, not a heavy press.",
    },
  },
];
